.config/.env.example
.gitignore
Makefile
README.md
client/package-lock.json
client/package.json
client/public/ie.js
client/public/index.html
openshift/server.bc.yml
server/db/schema.js

Allows low-permission service account to start build in OpenShift
Removes unused index from schema
Fixes CSP issue with inline script
Locks package version of `react-scripts`
Fixes name of GitHub OpenShift pull key

Hcap 30 os envs

---

client/public/ie.js

Working fine on my IE Tab Chrome plugin. Would be nice to get this thing tested on a real windows device.

removed Incompatible IE syntax

---

client/src/constants/routes.js
client/src/constants/validation.js
client/src/pages/public/Login.js
client/src/routes/index.js

Added login page mockup

---

client/src/components/employer-form/Summary.js
client/src/components/employer-form/index.js

Expanded by default when the form is active, closed by default (but still active) on the review page.

Hcap 74 form orientation

---

client/src/components/employer-form/OperatorInfo.js
client/src/components/employer-form/index.js
client/src/constants/validation.js
server/validation.js

Some minor changes included for form consistency across sections

Added orgbook search

---

Makefile
openshift/patroni.bc.yml
openshift/patroni.dc.yml
openshift/patroni.prep.yml
openshift/server.bc.yml
openshift/server.dc.yml

Patroni templates
Build in `-tools` namespace

Hcap 81 openshift patroni

---

client/src/pages/public/EmployerLanding.js

- changed routing to bypass this screen
- updated button text

Removed login screen for employers

---

client/src/components/employer-form/BaselineList.js
client/src/components/employer-form/SiteInfo.js
client/src/components/employer-form/index.js
client/src/components/fields/RenderTextField.js
client/src/constants/validation.js
server/validation.js

https://freshworks.atlassian.net/browse/HCAP-89
https://freshworks.atlassian.net/browse/HCAP-88

otherSite and workforce type fix

---

client/src/pages/public/EmployerLanding.js

Updated the content of the landing page with what was provided in the
new word document. We may merge this and the next page together later.

HCAP-93 Update Landing Page Content

---

README.md

The readme was out of date. Updated the build and run commands for running the app locally while hanging out on SU link with @ashtonmeuser and @mauriciofreshw

Update README with instructions to build and run the application

---

client/src/components/employer-form/HcapRequest.js
client/src/components/employer-form/Review.js
client/src/components/employer-form/index.js
client/src/constants/validation.js
server/validation.js

* Updated copy
* Changed title on page
* Changed title on stepper

HCAP-97 Update HCAP Request Section

---

client/src/components/employer-form/BeforeYouBegin.js
client/src/components/employer-form/StaffingChallenges.js

* Updated content on the before you begin page

HCAP-112-Copy-Changes

---

client/src/components/employer-form/Review.js
client/src/constants/validation.js
server/validation.js

Officially the worst PR
Expected behaviour is that users can leave every field blank, but if they enter values in a field the validation rules apply

Hcap 111 validation optional

---

client/public/index.html
client/src/constants/validation.js
server/validation.js

Fixed backend validation and removed unfurled description

Misc fixes

---

client/src/components/employer-form/BeforeYouBegin.js
client/src/components/employer-form/SiteInfo.js
client/src/components/employer-form/WorkforceBaseline.js
client/src/components/employer-form/index.js
client/src/constants/validation.js
server/tests/employer.form.test.js
server/validation.js

Some small copy updates from the business area, plus removal of the site postal code field

Copy updates, removed site postal code

---

Makefile
openshift/keycloak.prep.yml
openshift/server.dc.yml

This updates our OCP templates to add the Keycloak secrets
Next PR for HCAP-193 will include the updates to the FE/BE to rely on these

HCAP-163: Add env secrets for keycloak

---

client/src/components/generic/CheckPermissions.js
client/src/utils/permissions.js

Update Check permission message based on current role.

[HCAP-215][client] HA access request received message

---

client/src/pages/private/Admin.js
client/src/pages/private/EOIView.js
client/src/pages/private/EOIViewDetails.js
server/server.js

Just removing this permission for now, as it's intended to ship with matching between users and specific sites.

Temporarily disabled private employer access to EOIs until later matching

---

server/package-lock.json
server/package.json
server/server.js
server/services/participants.js
server/validation.js

Update participates validation schema, processing and parsing.

[HCAP-224] Refactor and transform participants data. 

---

Makefile
client/src/pages/private/ApplicantView.js
server/services/participants.js
server/validation.js

1. For HA/Employers Filtering participants list based on interested and crcClear values
2. Fix participants view issues
3. Add make utility to clean local deployment.

[HCAP-220][HCAP-234] Implement participant view restriction and fix issues.

---

client/src/components/generic/Table.js
client/src/pages/private/ParticipantView.js
server/db/schema.js
server/keycloak.js
server/migrations/1607725149661_change-column-type.js
server/server.js
server/services/participants.js
server/tests/participant.form.test.js

A few adjustments have been done to avoid some react weirdness:
1 - Columns with buttons which the onClick apply changes to the current page should be rendered on the Table component to avoid a chain of dependencies with global methods like `openToast`.
~~2 - If your function relies on the value of a given state outside a render, that value should be accessed through a reference (useRef) and not the state directly, unless you are 100% sure about your state value.~~ (not necessary anymore due to the last push)

Hcap 222 engage with participants

---

client/src/pages/private/ParticipantView.js
server/server.js

Hcap 253 multiple regions fix

---

client/src/components/generic/TableFilter.js
client/src/pages/private/EOIView.js

Filters by 'None' according to a special case where anything that evaluates to True is removed.

HCAP-229-Filter-By-None

---

server/keycloak.js
server/server.js

Logging finished for GET and POST from the participants API

Hcap 24X logging

---

client/src/pages/private/EOIViewDetails.js
server/server.js

logs accesses to the detail view of an EOI

Hcap 246 log eeoi detail

---

client/src/constants/routes.js
client/src/pages/private/Admin.js
client/src/pages/private/ReportingView.js
client/src/routes/index.js
server/server.js
server/services/reporting.js

Everything is complete except for participants hired by each health authority.

Hcap 189 v2 milestone reporting

---

client/src/constants/theme.js
client/src/pages/private/EOIViewDetails.js
client/src/pages/private/ParticipantView.js

This feature represents the foundation of the tabs and how we can manipulate it the way it is for now, currently only 2 tabs fully working.

Added tabs

---

client/src/components/generic/Table.js
client/src/pages/private/ParticipantView.js

I still need to fix a bug on tablepagination throwing an error on page reset, but navigation is functional.

Hcap 268 table navigation v2

---

.github/workflows/test.yml
Makefile
cypress/support/commands.js
package-lock.json
package.json

Cypress test suite can be activated by tagging cypress or on PR into master branch!

Hcap 256 cypress in pipeline

---

client/src/pages/private/EOIView.js
client/src/pages/private/ParticipantView.js
cypress/integration/EOIView.spec.js
cypress/integration/participantView.spec.js
cypress/support/commands.js

MoH and Superuser get all locations by default

Added tests for participant and EOI views

---

client/src/components/generic/DebounceTextField.js
client/src/pages/private/ParticipantView.js
server/server.js
server/services/participants-helper.js
server/services/participants.js
server/tests/participant.form.test.js

This PR also contains a refactorization of the `getParticipants` function using the Builder pattern.

HCAP-314 search email and last name

---

client/src/pages/private/ParticipantView.js
server/services/participants-helper.js
server/services/participants.js
server/tests/participant.form.test.js
server/validation.js

Note: Sorting by status does not function as intended.

Cumulative Status for MoH complete

---

server/services/participants-helper.js
server/services/participants.js
server/tests/participant.form.test.js

Added broad hired status for MoH

---

client/src/components/fields/RenderCheckbox.js
client/src/components/fields/RenderDateField.js
client/src/components/modal-forms/NewParticipantForm.js
client/src/components/modal-forms/index.js
client/src/constants/validation.js
client/src/pages/private/ParticipantView.js
cypress/integration/participantView.spec.js
cypress/support/commands.js
server/server.js
server/tests/participant.form.test.js
server/validation.js

Also added associated cypress and npm tests

Added functionality for manually adding hired participants

---

client/src/components/modal-forms/EditParticipantForm.js
client/src/components/modal-forms/index.js
client/src/constants/validation.js
client/src/pages/private/ParticipantView.js
cypress/integration/participantView.spec.js
cypress/plugins/index.js
cypress/support/commands.js
server/server.js
server/services/participants.js
server/tests/participant.form.test.js
server/validation.js

Big PR... aside from adding the EditParticipant form I also slimmed down some of the tests and accidentally unindented a couple of HTML blocks - gonna have to find some way to improve that moving forwards.

Hcap 323 update participant

---

client/src/components/modal-forms/NewParticipantForm.js
client/src/constants/validation.js
client/src/pages/private/ParticipantView.js
server/validation.js

Note: Could not fully test locally as I don't have access to KC right now 😭

Added validation for other site type

---

client/src/pages/private/ParticipantView.js
client/src/utils/fuzzyDateOffset.js
client/src/utils/index.js
cypress/integration/participantView.spec.js
cypress/support/commands.js
server/services/participants.js
server/tests/participant.form.test.js
server/validation.js

Sorting doesn't work properly yet.

Hcap 340 freshness

---

client/src/components/employer-form/BeforeYouBegin.js

Fixed link

---

client/src/pages/private/SiteViewDetails.js

The diff looks horrible with default settings - the Link import was changed and Card was added - the only change to the actual page is wrapping the content in the Card

Styling updates on site details

---

client/src/components/modal-forms/EditSiteForm.js
client/src/constants/validation.js
client/src/pages/private/SiteViewDetails.js
server/validation.js

Added missing fields, updated validation, button hidden for HAs

Site Details Edit updates

---

README.md

Hcap 358 rejected report

---

client/src/pages/private/SiteViewDetails.js
server/services/employers.js
server/tests/employer.form.test.js

Still working on the tests, but the actual implementation is up for review

HCAP and Non-HCAP hires are displayed in SiteDetailView

---

cypress/integration/participantView.spec.js
server/package.json
server/scripts/participant-stats-no-offers.js
server/services/reporting.js

output is on the console, not yet into CSV

Hcap 392 extract report

---

.gitignore
client/src/pages/private/SiteParticipantsTable.js
client/src/pages/private/SiteViewDetails.js
server/server.js
server/services/participants.js
server/tests/employer.form.test.js

Still a WIP, most logic is in place but still needs to be cleaned up

Hired Participants Are displayed on SiteDetailsView

---

server/migrations/1615361765942_index-optimization.js

Added traditional indexes on Id/status columns and a [gin](https://www.postgresql.org/docs/9.1/textsearch-indexes.html) index for quick text match search over `preferredLocation`

Performance fix

---

cypress/integration/participantView.spec.js
cypress/support/commands.js
server/migrations/1615337215944_boolify-callback.js
server/server.js
server/services/participants.js

Actually went really smoothly once I stopped overcomplicating it!

Migrating string falses to boolean

---

client/src/components/fields/RenderTextField.js

Accessibility fixes

---

client/src/components/employer-form/index.js
client/src/components/modal-forms/NewSiteForm.js
client/src/components/modal-forms/index.js
client/src/components/participant-form/index.js
client/src/constants/validation.js
client/src/pages/private/ParticipantTable.js
client/src/pages/private/SiteTable.js
client/src/pages/private/SiteView.js
client/src/pages/private/SiteViewDetails.js
server/validation.js

- Added create site button + modal for MOH
- Cleaned up BE phone validation to allow null
- Removed unreachable toast errors
I also touched a bunch of files where I ended up reverting my changes, but in the touching my IDE cleaned up some trailing whitespace so you might want to change your view settings to ignore that!

HCAP-389: Create site FE

---

client/src/components/participant-form/Fields.js

https://freshworks.atlassian.net/browse/HCAP-495

HCAP-495 Update PEOI copy

---

client/src/components/generic/Header.js

Modify logo alt for better clarity
https://freshworks.atlassian.net/browse/HCAP-421

HCAP-421 Add link to BC homepage

---

client/src/components/participant-form/Fields.js

https://freshworks.atlassian.net/browse/HCAP-467
This PR is a good opportunity to talk about styles :D 
I've hardcoded colors here based on what I saw in the [ticket](https://freshworks.slack.com/archives/C011G18PW5S/p1618267252263300?thread_ts=1618248466.243700&cid=C011G18PW5S), normally I'd like all of these colors to be defined in the theme. What do you think?
Also, do you go pixel-perfect with designs or do you use the closest approximation with MUI components? Ideally our MUI theme should be 1-1 with designs and there wouldn't be too much hand-CSS to write.
Hex or RGB?

HCAP-467 Update PEOI Contact

---

client/src/pages/public/ParticipantConfirmation.js

https://freshworks.atlassian.net/browse/HCAP-518
Skipping dev test due to simplicity of the change

HCAP-518 Remove timeline in confirmation

---

client/src/pages/private/UserView.js

https://freshworks.atlassian.net/browse/HCAP-451

HCAP-451 Show 0/null allocation sites

---

client/src/components/fields/RenderAutocomplete.js
client/src/components/modal-forms/NewParticipantForm.js

https://freshworks.atlassian.net/browse/HCAP-410

HCAP-410 non portal hire site autocomplete + sorting

---

client/src/pages/private/ParticipantTable.js

This is what I was thinking for those functions to reduce the wordiness

Expand simplification to other functions

---

client/src/pages/private/ParticipantTable.js
client/src/utils/object.js

Added trimming to search fields. 
Added checks so that the page will not refresh if the text does not change after refresh

Added timming to seach fields

---

client/src/components/participant-form/Fields.js

https://freshworks.atlassian.net/browse/HCAP-526
Update PEOI contact text to:
> Contact a Health Career Access Program agent at HCAPInfoQuery@gov.bc.ca
> Service is available from 8:00 am - 4:30 pm Pacific Time Monday through Friday
Email is clickable mailto link

HCAP-526 Add email to PEOI contact message

---

.husky/_/husky.sh
.husky/pre-commit
package-lock.json
package.json
server/package-lock.json
server/package.json

This is just for prettier, ended up running into some weirdness with the linters/lint-staged so I'm going to keep it brief for now. Would love to pick this back up and get the whole suite running pre-commit.
Removed lint-staged from server for streamlining (and I don't think I've seen it activate for me yet?)

Prettier pre-commit hook

---

server/migrations/1620672944865_update-triggers.js
server/package-lock.json
server/package.json

Basically just rewrote the update_postal_code triggers to add a thing or two.

firstly, fixed farness fathoming. Furthermore, finalized fuzzy matching

---

server/migrations/1620672944865_update-triggers.js

gotta cast siteID as an integer

speedy gonzales bugfix

---

server/db/db.js
server/package.json
server/scripts/get-email-list.js

Added a simple script to get all unique email addresses from participants that are: 
- 6 weeks old or older
- Still active in the program 
- At least one application is not hired

Hcap 536 filter participants for email blast

---

client/src/pages/private/SiteTable.js

https://freshworks.atlassian.net/browse/HCAP-498?focusedCommentId=49212

HCAP-498 - Remove RHO column on Site Table

---

openshift/patroni.bc.yml

https://freshworks.atlassian.net/browse/HCAP-500
Propose simply adding a reminder in Slack to update the fork monthly, otherwise we need to figure out some sort of automation. It would be fairly simple but would require a server to run the chron job.

HCAP-500 - Use FreshworksStudio Fork

---

README.md

I have one question about excel sheets commented on the ticket: https://freshworks.atlassian.net/browse/HCAP-522

HCAP-522 Onboarding

---

client/src/constants/confirmInterestConstants.js
client/src/pages/public/ConfirmInterest.js
client/src/routes/index.js
server/migrations/1620932907414_add-otps.js
server/server.js
server/services/participants.js

https://freshworks.atlassian.net/browse/HCAP-582

HCAP-582 Confirm Interest Endpoint

---

server/migrations/1620932907414_add-otps.js

looks like new edition of this query didn't give the exact results we were after, going to ignore the performance hit as this is only going to be run once.

confirm interest migration: revert to previous query

---

.husky/pre-commit
client/.eslintrc
client/package-lock.json
client/package.json
client/src/components/generic/Header.js
package-lock.json
package.json

+ fix warning about lint/react version
Removed vestigial onClick from logo

HCAP-587 - add jsx a11y eslint plugin 2/3

---

Makefile
README.md
server/package.json
server/scripts/feed-participants.js
server/scripts/feed-sites.js

https://freshworks.atlassian.net/browse/HCAP-522
- Makefile commands for seeding
- Participant seed script, completely different implementation but similar functionality to `feed-sites.js`
- Update docs with new functionality
- Fix feed-sites where it hangs on successful completion

HCAP-522 Seed Scripts

---

server/scripts/sendEmailBlast.js

+Semantic tags
https://freshworks.atlassian.net/browse/HCAP-604

HCAP-604 Plaintext email link

---

client/package-lock.json
package-lock.json
package.json
server/package-lock.json
server/package.json

- Locks package versions
- Updates package-lock files (they were out of step)

Lock Versions + Rerun npm i

---

server/scripts/sendEmailBlast.js

https://freshworks.atlassian.net/browse/HCAP-654

HCAP-654 remove plaintext versions of links

---

server/scripts/sendEmailBlast.js

https://freshworks.atlassian.net/browse/HCAP-658

HCAP-658 Fix Mongo Logging

---

client/src/pages/private/ParticipantTable.js

Added padding bottom to site distance calculation section

---

Makefile
mongodb-recreate-and-restore.md
mongodb-recreate-and-restore.txt
openshift/mongo.helm.yml
openshift/server.dc.yml

Okay, phew! Finally got this whole process documented and tested on dev.
The new mongo instance has 18953 records, which seems like a pretty good number to me though I didn't confirm whether or not that is exactly what we're looking for. Looking forward to trying this out on test!

Mongo Transferral Process

---

Makefile
README.md
client/src/pages/private/ParticipantTable.js
client/src/utils/prettifyStatus.js
server/services/participants-helper.js
server/services/participants.js

-----
1. Display withdrawn status in managed participant view
2. Allow archive
Ticket: [HCAP-354](https://freshworks.atlassian.net/browse/HCAP-354)
N.B. - 
1.  Changes also fix bug: [HCAP-689](https://freshworks.atlassian.net/browse/HCAP-689)
2. Removed existing interest filter => 'body.interested': 'yes'

[HCAP-#354][client][server] Display withdrawn status for HA/Employer

---

client/src/pages/private/ParticipantTable.js

Move Location Selection Logic (HCAP-660 #5) 

---

client/src/utils/prettifyStatus.js
server/server.js
server/services/employers.js
server/services/reporting.js

----
1. Remove duplicate hire/archive candidate from all reporting
2. Add hire/withdrawn participant details in hiring report.
Ticket: [HCAP-#424](https://freshworks.atlassian.net/browse/HCAP-424)

[HCAP-424][api][client] Handling Hire + Archive Participant in reporting

---

.github/workflows/config-prod.yml
.github/workflows/config-test.yml
.github/workflows/config.yml
Makefile
openshift/ches.prep.yml
openshift/server.dc.yml
openshift/universal.bc.yml

----
1. Create make alias for testing deploy config change
2. Create make alias for process and apply deployment config change
3. Create new github workflow config.
Ticket: [HCAP-585](https://freshworks.atlassian.net/browse/HCAP-585)

[openshift][workflow][Makefile][HCAP-#585] Deploy config changes

---

server/services/employers.js
server/services/reporting.js

Fix counting issue in site detail view regarding no-hcap hire.
Issue: [HCAP-705](https://freshworks.atlassian.net/browse/HCAP-705)

[HCAP-#705] Fix non-hcap duplicate hire counting in site detail view.

---

client/src/components/modal-forms/ArchiveHiredParticipantForm.js
client/src/constants/archiveParticipantsConstants.js
client/src/constants/participantTableConstants.js

Added toast popup
Fixed a couple of typos
Nixed future archived

702-704, fixes for participant withdrawal 

---

server/services/participants.js

Changing participant interested flag to withdrawn.
Ticket: [HCAP-707](https://freshworks.atlassian.net/browse/HCAP-707)
Story: [HCAP-412](https://freshworks.atlassian.net/browse/HCAP-412)

[HCAP-#707] Saving interested while creating archived / duplicate status.

---

client/src/components/modal-forms/ArchiveHiredParticipantForm.js
client/src/constants/archiveParticipantsConstants.js
client/src/constants/participantTableConstants.js
client/src/constants/validation.js
client/src/utils/prettifyStatus.js
server/validation.js

Fixed validation filters and typos

Hcap v2.19 hotfixes

---

client/src/pages/private/SiteParticipantsTable.js
server/server.js

Added missing AC for 412. 
Health Authorities can now withdraw candidates from the Site details page

Hcap 412 add withdraw to site details view

---

client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTable.js
client/src/utils/prettifyStatus.js
server/services/participants.js

Ticket: [HCAP-707](https://freshworks.atlassian.net/browse/HCAP-707)

[HCAP-#707] Saving participant interested flag for hire/archived case

---

client/src/pages/private/SiteParticipantsTable.js
client/src/pages/private/SiteViewDetails.js

---
Ticket: [HCAP-718](https://freshworks.atlassian.net/browse/HCAP-718)
1. Fix reload issue of site detail view
2. Some minor code improvement

[HCAP-#718] BugFix: Fix reload issue of site detail view

---

openshift/server.dc.yml

Fix mongo user name in deployment config

[HotFix] Fix mongo user name issue

---

.github/workflows/build.yml

1. Integrate OWSAP ZAP scan with `dev` build and deploy workflow
2. Add additional health check setp/action
Ticket: [HCAP-709](https://freshworks.atlassian.net/browse/HCAP-709)

[HCAP-#709]: Add owsap zap scan with build and deploy workflow

---

client/src/constants/routes.js
client/src/pages/private/ParticipantLoginSuccess.js
client/src/pages/public/ParticipantLogin.js
client/src/routes/index.js
server/keycloak.js

PR is ready to go 
We may need to chat about the link to the BCSC virtual card set up. The link in the designs goes nowhere. The one I added is the result of a quick google search.

HCAP-512 BC Services card 

---

client/src/pages/public/ParticipantForm.js
client/src/pages/public/ParticipantLogin.js
client/src/routes/index.js

Added login button to header

---

client/src/components/generic/Header.js
client/src/pages/public/ConfirmInterest.js
client/src/pages/public/ParticipantConfirmation.js
client/src/pages/public/ParticipantLogin.js

Fixed the spacing on smaller screens and fixed some typos in the content for the ParticipantTable page

Fixed typos and mobile styling

---

Makefile
server/services/participants.js
server/tests/participant.service.test.js

---
1. Fix bug
2. Improve efficiency
3. Add more test items
---
Ticket: [HCAP-517](https://freshworks.atlassian.net/browse/HCAP-517) | [HCAP-738](https://freshworks.atlassian.net/browse/HCAP-738)

[HCAP-517][HCAP-738] Linking participants with user after first time login

---

openshift/server.dc.yml
server/error-handler.js
server/keycloak.js
server/logger.js
server/main.js
server/package-lock.json
server/package.json
server/server.js
server/services/health-check.js

------
1. Add livenessProbe
2. Increase number of replicas
3. Add retry at KeyCloak service layer
4. Update logs with more info and timestamp
5. Add more logs
6. Add express logger
7. Add health check api
Ticket: [HCAP-749](https://freshworks.atlassian.net/browse/HCAP-749)
--

[SOS][Prod-HotFix] Update deployment config

---

client/src/components/employer-form/BeforeYouBegin.js

https://freshworks.atlassian.net/browse/HCAP-717?atlOrigin=eyJpIjoiNjM5MjhkZGEwYzIyNGExYWEwNjJjZDUzMWE2N2U0MWYiLCJwIjoiaiJ9

HCAP-717 | Copy updated

---

client/src/components/generic/Toast.js
client/src/components/participant-form/Fields.js
client/src/components/participant-form/index.js
client/src/constants/routes.js
client/src/constants/validation.js
client/src/hooks/index.js
client/src/hooks/useQuery.js
client/src/pages/private/ParticipantEOI.js
client/src/pages/private/ParticipantLanding.js
client/src/pages/private/ParticipantWithdrawConfirm.js
client/src/routes/index.js
server/error-handler.js
server/routes/index.js
server/routes/participant-user.js
server/server.js
server/services/participants.js
server/tests/participant.service.test.js
server/utils.js
server/validation.js

-----
1. Create view PEOI From Participant landing
2. Edit selected fields in PEOI
3. Withdraw for PEOI
4. Bug Fixes (HCAP-748)
5. Add some small utilities
6. **Add new route structure in express api layer**
Ticket: [HCAP-516](https://freshworks.atlassian.net/browse/HCAP-555) | [HCAP-555](https://freshworks.atlassian.net/browse/HCAP-555) | [HCAP-748](https://freshworks.atlassian.net/browse/HCAP-748)

[HCAP-516][HCAP-555] Edit and With PEOI for BCSC User

---

client/src/constants/archiveParticipantsConstants.js
client/src/constants/validation.js
docker-compose.dev.yml

Updated front end validation for the archive candidate date picker

Fixed validation on date picker

---

client/src/constants/validation.js
docker-compose.dev.yml

-----------------------------------------------
1. Add required validation for PEOI update
2. Fix Docker(v20.*) env issue with `LAST_COMMIT`. Change to `COMMIT_SHA`
Ticket: [HCAP-761](https://freshworks.atlassian.net/browse/HCAP-761)

HCAP-761 | Add required validation for PEOI update

---

Dockerfile
client/Dockerfile.dev
server/package-lock.json

Just removing references to node:14-alpine and replacing them with bitnami sources

bitnami is the new black

---

client/src/components/generic/Header.js
client/src/pages/private/ParticipantLanding.js

I implemented a drop-down menu without giving much consideration to aesthetics, I'm expecting that this might need some refinement before it goes to production.

Hcap 751 peoi mobile overlap

---

.github/workflows/build.yml
Dockerfile

Switch to **registry.access.redhat.com/ubi8/nodejs-14:1** as base image to build client/server.

HCAP-774 | Fix base image pull limit issue.

---

.husky/npm.sh
.husky/pre-commit
package.json

- Force husky to use bash for shell scripts
- Add `--staged` flag for pretty-quick [formats and then restages changes](https://github.com/azz/pretty-quick#--staged-only-git)
- rename script

Update husky hooks

---

client/src/pages/private/ParticipantTable.js

View my candidates button now correctly changes tab.

Fixed My Candidates modal not changing tabs

---

client/src/components/modal-forms/ArchiveHiredParticipantForm.js
client/src/constants/validation.js
client/src/pages/private/ParticipantTable.js
client/src/pages/private/SiteParticipantsTable.js
server/server.js
server/services/reporting.js
server/validation.js

Added intent to rehire radio box group to Archive Participant workflow.

Hcap 773 intent to rehire

---

openshift/sysdig.yml
server/server.js

Add Sysdig user provisioning CRD - https://developer.gov.bc.ca/OpenShift-User-Guide-to-Creating-and-Using-a-Sysdig-Team-for-Monitoring
Error Simulation Endpoint.

[HCAP-768] Alerting poc

---

server/routes/index.js
server/routes/milestone-report.js
server/tests/milestone-report.e2e.test.js
server/tests/util/keycloak.js

----
1. Refactor route
2. Add api e2e tests
--

HCAP-706 | HCAP-801 | Refactor milestone report route

---

server/routes/milestone-report.js
server/tests/milestone-report.e2e.test.js

-----
1. Fix issue
2. Update tests
--

HCAP-706 | Fix milestone api data format issue

---

client/src/pages/private/PSITable.js

because it wasn't supposed to be there

Removed None

---

client/src/constants/archiveParticipantsConstants.js
client/src/constants/validation.js
client/src/pages/private/PSIView.js
cypress/integration/psiDetailView.spec.js

Most of these were small, one line adjustments.
Tickets Addressed:
https://freshworks.atlassian.net/browse/HCAP-810?atlOrigin=eyJpIjoiNGY2Zjg5MGFkMWU2NDU2Y2FkMTQ4NWY0OTVhYTkzYmMiLCJwIjoiaiJ9
https://freshworks.atlassian.net/browse/HCAP-811?atlOrigin=eyJpIjoiODEyNjY0YzhmMjVjNDdhYTg1N2MxMGRmNzE1NWI5MjkiLCJwIjoiaiJ9
https://freshworks.atlassian.net/browse/HCAP-812?atlOrigin=eyJpIjoiN2JlMDMyMTZlOWJlNDAyYmE3MGJmMWU3YjA5NWQ1MjQiLCJwIjoiaiJ9
https://freshworks.atlassian.net/browse/HCAP-813?atlOrigin=eyJpIjoiNDJhMzMyMDc2MGRkNGRlNmJjMmU3NDljNzBjM2I0MzkiLCJwIjoiaiJ9
https://freshworks.atlassian.net/browse/HCAP-815?atlOrigin=eyJpIjoiZmUxOTk4NjBlZGE4NGIxMjhmMjdkYjcyMTNjNTY4MTYiLCJwIjoiaiJ9

HCAP-810 | HCAP-811 | HCAP-812 | HCAP-813 | HCAP-815 - Validation changes for the Cohort Form

---

server/routes/participant-user.js
server/services/participants-helper.js
server/services/participants.js

When a user is withdrawn, their status is no-longer changed. 
Removed my old overly complicated withdrawn status patch for 696. 
NOTE: While initially I intended to address HCAP-722 here, after talking with Surabhi, more clarification is needed, so I have flagged the ticket and put it on hold. This PR is only for 723.

Hcap 723 notification on archival

---

client/src/components/generic/Table.js
client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTable.js
client/src/providers/ParticipantsContext.js

* When you change tabs, the current page is set to zero 
* removed the Table components internal page state because it was causing issues. 
* Moved changing page from the main reducer to the tab reducer because changing tabs now changes page state.

Hcap 720 page skip issue

---

client/src/pages/private/CohortTable.js
client/src/pages/private/PSIViewDetails.js

Removed some dead-end code since it wasn't fully implemented
Addresses the following bugs:
https://freshworks.atlassian.net/secure/RapidBoard.jspa?rapidView=206&modal=detail&selectedIssue=HCAP-816
https://freshworks.atlassian.net/secure/RapidBoard.jspa?rapidView=206&modal=detail&selectedIssue=HCAP-809

HCAP-816 | HCAP-809 | Removed unfinished TODOs

---

client/src/components/generic/Table.js
client/src/components/modal-forms/NewPSIForm.js
client/src/constants/validation.js
client/src/pages/private/PSIView.js
client/src/pages/private/ParticipantTable.js
cypress/integration/psiView.spec.js
server/services/post-secondary-institutes.js
server/validation.js

Changes: 
- Removed Pagination component from all tables except Participants. 
- Add PSI modal remains open on duplicate submission.
- PSI -> street address and city are now optional fields
Addresses the following tickets:
https://freshworks.atlassian.net/browse/HCAP-807?atlOrigin=eyJpIjoiNGYxZTdhNzNkMmFmNGRhOTg2M2NkNmIyNDBkOTY3MTIiLCJwIjoiaiJ9
https://freshworks.atlassian.net/browse/HCAP-814?atlOrigin=eyJpIjoiNzdmMzU4OTE0OGI0NDZiNzgxYzMwZjViMzkzZTM3ZjIiLCJwIjoiaiJ9
https://freshworks.atlassian.net/browse/HCAP-820?atlOrigin=eyJpIjoiN2U5M2UwYTEwMTlmNDMwNmE0NGI3NjAyNGM4MWNhNzUiLCJwIjoiaiJ9

HCAP-807 | HCAP-814 | HCAP-820 - PSI form changes

---

client/src/components/generic/Table.js
client/src/pages/private/ParticipantTable.js
client/src/providers/ParticipantsContext.js

My fix for 720 was causing other page components to break (HCAP-822). 
I am sick today, but I don't want an issue I introduced to block a possible release. This PR reverts my fix for 720. 
I have started work on a proper fix for both on the branch HCAP-822_table_fix.

HCAP-822 Reverting HCAP-720 changes

---

client/src/pages/private/PSIView.js

filtering out closed cohorts before summing remaining seats.
Addressing the following ticket: 
https://freshworks.atlassian.net/browse/HCAP-823?atlOrigin=eyJpIjoiZjg0NGZjODMwZGY0NGQ3ZThhMWRlZDg5YWI2MjU1MjYiLCJwIjoiaiJ9

HCAP-823 | Calculating Available Seats from Open Cohorts

---

client/src/pages/private/PSIView.js
cypress/integration/psiDetailView.spec.js
cypress/integration/psiView.spec.js

replaced "PSI" with "Post-Secondary Institute" on Add PSI button.
Addresses: https://freshworks.atlassian.net/browse/HCAP-829?atlOrigin=eyJpIjoiNjc0MmM3NGRmYjkyNDJjNmE2ODFjYmNjOTA4NTUwNjYiLCJwIjoiaiJ9

HCAP-829 | PSI Button Text

---

client/src/components/generic/Table.js
client/src/pages/private/ParticipantTable.js
client/src/providers/ParticipantsContext.js

It looks like stripping out pagination from all the other tables fixes 822, so I am re-adding my changes for 720. 
I've tested this out manually a fair bit and it looks. good. 
I have some concerns about this though, mainly around performance if we have large amounts of data on prod. 
Please let me know what you think.

Hcap 720 page skip fix

---

client/src/pages/private/PSIViewDetails.js

Small fixes addressing the following ticket:
https://freshworks.atlassian.net/browse/HCAP-832?atlOrigin=eyJpIjoiMTA0NzcxYTcxNDY1NDg2NzgyY2YwNmZlMzRlNzZlMzAiLCJwIjoiaiJ9

HCAP-832 | Added minimum width and default values

---

client/src/constants/validation.js
client/src/pages/private/PSIView.js

Addresses the following tickets:
https://freshworks.atlassian.net/browse/HCAP-815?atlOrigin=eyJpIjoiMWI0ZGUwMDk0N2U5NDAwNTgyZWYyZmM0M2RkMzlkMTciLCJwIjoiaiJ9
https://freshworks.atlassian.net/browse/HCAP-835?atlOrigin=eyJpIjoiOGU1MzdkMmY1ODA0NDJmODk5YWNjMzZhYTJkMTNjNmYiLCJwIjoiaiJ9
https://freshworks.atlassian.net/browse/HCAP-836?atlOrigin=eyJpIjoiNDRmOGIyMGMyZWUzNGFiM2FkYzUzZGQ1OWFiZjg1MjkiLCJwIjoiaiJ9

HCAP-815 | HCAP-835 | HCAP-836 - cohort adjustments

---

server/services/participants.js

https://freshworks.atlassian.net/browse/HCAP-804
1. Query for previously hired participants associated with given siteID
2. Use that list of participants to find withdrawn statuses

HCAP-804 | Rewrite query for withdrawn participant by siteID

---

client/src/constants/validation.js

https://freshworks.atlassian.net/browse/HCAP-836
to

HCAP-836 | Add validation error for cohort size = 0

---

client/src/constants/validation.js

[Cohort size > no error message on clicking submit without entering any value](https://freshworks.atlassian.net/browse/HCAP-847)
- Revert validation change
- Remove `psiId` from validation (not part of form)
- Just use `required` for cohort size validation

HCAP-847 | add cohort validation

---

client/src/constants/routes.js
client/src/pages/private/ParticipantDetailsView.js
client/src/pages/private/ParticipantTable.js
client/src/routes/index.js
client/src/utils/gen-util.js
client/src/utils/index.js

1. Add draft participant details page
2. Add basic navigation to the page
Ticket: [HCAP-675](https://freshworks.atlassian.net/browse/HCAP-675)

HCAP-675 | Participant details Page, basic navigation

---

client/src/pages/private/ParticipantDetailsView.js

-----
1. Add basic page layout
2. Integrate with api call

HCAP-675 | Add  basic functional page layout with data integration

---

client/src/pages/public/ParticipantForm.js
server/routes/participant.js

This is branched off from the v2.21 tag. 
I believe that was the last release. 
This PR blocks of the PEOI form.

HCAP-851 | Closing off form

---

client/src/constants/routes.js
client/src/pages/private/ParticipantDetailsView.js
client/src/pages/private/ParticipantTable.js
client/src/pages/private/SiteParticipantsTable.js
server/middleware/access-logger.js

-------
1. Fix wrong participant view from site-details
2. Fix Breadcrumb
3. Add postal code fsa
4. Remove participant details viewing from site-view for MoH/Superuser
Main Ticket: [HCAP-675](https://freshworks.atlassian.net/browse/HCAP-675)
Bugs: [HCAP-864](https://freshworks.atlassian.net/browse/HCAP-864) |  [HCAP-866](https://freshworks.atlassian.net/browse/HCAP-866) |  [HCAP-867](https://freshworks.atlassian.net/browse/HCAP-867) | [HCAP-868](https://freshworks.atlassian.net/browse/HCAP-868)

HCAP-675 [HCAP-864 | HCAP-866 | HCAP-867 | HCAP-868 ] |  Bug fixes

---

server/keycloak.js
server/logger.js
server/main.js
server/middleware/access-logger.js
server/middleware/express-request-validator.js
server/routes/cohorts.js
server/services/health-check.js
server/tests/util/keycloak.js

https://freshworks.atlassian.net/browse/HCAP-843
- emit logs as json on non local 
- Update some log statements

[HCAP-843]  emit JSON logs in non local env

---

client/src/components/participant-details/index.js
client/src/components/participant-details/psi-cohort-table.js
client/src/components/participant-details/psi-cohort.js
client/src/constants/routes.js
client/src/pages/private/ParticipantDetailsView.js
client/src/routes/index.js

------
1. Create root component
2. Create router based tab control
Ticket: [HCAP-676](https://freshworks.atlassian.net/browse/HCAP-676)

HCAP-676 | Router based navigation creation for participant details view

---

client/src/pages/private/ParticipantTable.js
client/src/utils/prettifyStatus.js

I was going to tack these fixes to 850, but it looks like 850 is going to take longer than expected, so I am publishing these separately. 
I have removed the archive button from withdrawn participants in the hired candidates tab. 
Also I have fixed an issue where the `Acknowledge ` button was showing up in the archived candidates tab.

Hcap 873 874 withdraw notification bugs

---

client/src/components/generic/Page.js
client/src/components/participant-details/cohort-table.js
client/src/components/participant-details/psi-cohort-table.js
client/src/components/participant-details/psi-cohort.js
client/src/pages/private/ParticipantDetailsView.js
client/src/services/index.js
client/src/services/psi-cohort.js
server/keycloak.js
server/routes/post-secondary-institutes.js
server/services/post-secondary-institutes.js
server/tests/psi.e2e.test.js

Ticket: [HCAP-676](https://freshworks.atlassian.net/browse/HCAP-676)
1. Create table structure 
2. Integrate with Rest API

HCAP-676 | PSI-Cohort table Viewing from Participant Details Page

---

server/routes/cohorts.js
server/services/cohorts.js
server/tests/cohorts.e2e.test.js
server/tests/util/keycloak.js
server/tests/util/testData.js

1. Add api routes
2. Add service method
3. Add tests
Ticket: [HCAP-677](https://freshworks.atlassian.net/browse/HCAP-677)

HCAP-677 | Rest API to assign participant to a cohort

---

client/src/components/participant-details/cohort-table.js
client/src/components/participant-details/psi-cohort-table.js
client/src/components/participant-details/psi-cohort.js
client/src/pages/private/ParticipantDetailsView.js
client/src/services/participant.js
client/src/services/psi-cohort.js
server/logger.js
server/routes/cohorts.js
server/services/cohorts.js

------
(Final assignment of HCAP-677)
1. Fix some server side issue
2. Update client service layer
3. HA can assign participant from participant details page.
Ticket: [HCAP-677](https://freshworks.atlassian.net/browse/HCAP-677)

HCAP-677 | Front end implementation of Assign Cohort to a participant

---

client/src/pages/private/SiteParticipantsTable.js
client/src/pages/private/SiteViewDetails.js
cypress/integration/siteViewDetails.spec.js

Added a staleness flag to the SiteParticipants Table to signal that something has changed and should be updated.
https://freshworks.atlassian.net/browse/HCAP-787?atlOrigin=eyJpIjoiYTFhYzJhMmY1NTcxNGUxYWE5MzI4NzZiM2Y1ZDY2NTciLCJwIjoiaiJ9

Hcap 787 update site details

---

client/src/pages/private/SiteTable.js
cypress/integration/siteView.spec.js

Changed the default 'orderBy' value and wrote a test.
https://freshworks.atlassian.net/browse/HCAP-885?atlOrigin=eyJpIjoiOWExNjEzYjhiZGVmNDEzOWJjMjlhZTRlMDQwYTY3YzQiLCJwIjoiaiJ9

HCAP-885 | sort sites by name

---

client/src/pages/private/SiteParticipantsTable.js
server/routes/participant.js
server/services/participants.js

- Removed pending withdrawal status from employer actions route
- Added siteId to useEffect for the selected tab so that on load, the default tab will be the site details tab.
- Added HA to the acknowledge route to cover the case where a HA withdraws another HA's participant

Fixed various small issues.

---

client/src/pages/private/SiteParticipantsTable.js
server/routes/participant.js
server/services/participants.js

Fixed 906/907, looks like it was a site id issue
Added an error if the archived user could not be found.

HCAP- 906 / 907 hotfix

---

client/src/constants/archiveParticipantsConstants.js
server/validation.js

https://freshworks.atlassian.net/browse/HCAP-887?atlOrigin=eyJpIjoiNWYwNTJlYTkxMGQ0NDI4OWI2NzM4Nzg3NGM4M2M5N2YiLCJwIjoiaiJ9

HCAP-887 | Added new withdrawal reason

---

client/src/pages/private/ParticipantTable.js

https://freshworks.atlassian.net/browse/HCAP-886?atlOrigin=eyJpIjoiY2Q3ZThjNTk4ZmQwNGE4MWFmMjBkNTM3MjIyOGNhY2IiLCJwIjoiaiJ9

HCAP-886 | Only hiding last name and email filters on archived candidates

---

server/services/participants.js

I removed the block on searching emails and lastnames on the back end. 
Please look over the logic and check to make sure this is whats desired.

removed last name and email filter

---

client/src/pages/public/ParticipantLogin.js
server/server.js

Updated copy to match designs. 
Replaced "Sign in" with Login/ log in. 
Replaced awkward clickable box with a button

Hcap 876 bcsc login updates

---

client/src/pages/private/Admin.js
client/src/pages/private/PSIView.js
client/src/pages/private/PSIViewDetails.js
cypress/integration/login.spec.js
cypress/integration/psiView.spec.js
server/routes/post-secondary-institutes.js
server/routes/psi-cohorts.js
server/services/participants.js

Added Manage PSI and create PSI permissions to HA

HCAP-861, 862 Added HA permissions to psi workflows

---

.config/.env.example
client/src/pages/public/ParticipantForm.js
client/src/routes/index.js
docker-compose.dev.yml
docker-compose.test.yml
openshift/server.dc.yml
server/main.js
server/middleware/access-logger.js
server/routes/index.js
server/routes/participant.js

1. Add new env variable to identify application environment 
2. Add support of OpenShift DC
3. Add support for local / test app
4. As an example, enable participant form for test/dev
Ticket: [HCAP-870](https://freshworks.atlassian.net/browse/HCAP-870)

HCAP-870 |  Add new ENV variable to identify application environment 

---

client/src/pages/private/PSITable.js

Fixed an issue where HA's were only able to view PSI's in their regions.

Removed filtering limitations for the psi view

---

server/services/participants.js
server/tests/participant.landing.e2e.test.js
server/tests/util/keycloak.js

Enable api e2e tests for participant with seeded user for test.

HCAP-737 | Enable api e2e tests for participant

---

client/src/constants/routes.js
client/src/constants/validation.js
client/src/pages/private/ParticipantFullWithdrawPage.js
client/src/pages/private/ParticipantLanding.js
client/src/routes/index.js
server/services/participants.js

Added post withdrawal confirmation page
Prevented form submission without confirmation
Added some extra checks to prevent a 500 under strange data conditions during withdrawal
Fixed date formatting issue

HCAP-880 bug fixes

---

client/src/constants/archiveParticipantsConstants.js
server/routes/user.js
server/validation.js

1. Add new withdraw reason 'Issue with mandatory vaccination'
2. Fix one issue of patching user site details
Ticket: [HCAP-940](https://freshworks.atlassian.net/browse/HCAP-940)
Screen Shots

HCAP-940 | Add new withdraw reason

---

client/src/pages/private/ParticipantLanding.js
client/src/pages/private/ParticipantLandingEmpty.js

HCAP-877 Added empty peoi landing page

---

.github/workflows/test.yml

Checking to see if pipeline tests with new version

Changing test ubuntu version

---

client/src/pages/private/ParticipantLandingEmpty.js

Fixed some typos that I made for the empty participant landing page.

HCAP-969 Fixed typos and copy errors

---

client/src/pages/private/ParticipantLandingEmpty.js

https://freshworks.atlassian.net/browse/HCAP-969
Draft pending link location flag

HCAP-969 | Fix spelling error

---

client/src/pages/private/ParticipantEOI.js

------
Remove option to edit consent for POI update feature for BCSC users.
Ticket: [HCAP-783](https://freshworks.atlassian.net/browse/HCAP-783)

HCAP-783 | Bug Fix: Remove edit option for consent for POI

---

client/src/components/participant-form/Fields.js
client/src/components/participant-form/index.js
client/src/utils/isNonPortalHire.js

https://freshworks.atlassian.net/browse/HCAP-784
- Add helper method
- Set flag to determine non-portal PEOIs
- Conditionally render on new flag

HCAP-784 | Conditionally render fields for non-portal hire PEOIs

---

openshift/server.dc.yml

https://freshworks.atlassian.net/browse/HCAP-979

HCAP-979 | disable haproxy router cookie

---

client/src/pages/private/ParticipantEOI.js
client/src/pages/private/ParticipantWithdrawConfirm.js

This is my attempt at deciphering the different notes in the ticket
- New Withdraw button text
- New copy on the confirmation dialogue
- New styling + copy on success page

HCAP-882 | Withdraw design updates

---

client/src/pages/public/ParticipantLogin.js

Addresses `#1` for this ticket: https://freshworks.atlassian.net/browse/HCAP-879

HCAP-879 | PEOI Login: Improve spacing and responsive behaviour

---

client/src/pages/private/ParticipantEOI.js
client/src/pages/public/ParticipantLogin.js

`#2` in this ticket: https://freshworks.atlassian.net/browse/HCAP-879

HCAP-879 | PEOI Button spacing

---

client/src/pages/private/ParticipantActionSuccess.js
client/src/pages/private/ParticipantWithdrawConfirm.js
cypress/integration/participant-landing.spec.js

https://freshworks.atlassian.net/browse/HCAP-879

HCAP-879 | Confirm success spacing adjustment

---

client/src/components/participant-form/Fields.js

I forgot to add a key to the mapped field 😢 
Relates to https://freshworks.atlassian.net/browse/HCAP-931

Fix React error on view PEOI 

---

client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTable.js
cypress/fixtures/participantTableTabs.json
server/services/participants.js

https://freshworks.atlassian.net/browse/HCAP-986

HCAP-986 | remove indigenous identity column

---

client/src/components/participant-form/DisabledLanding.js
client/src/components/participant-form/EmailSubmissionForm.js
client/src/constants/validation.js
client/src/pages/private/ParticipantLanding.js
client/src/pages/public/ParticipantForm.js
client/src/pages/public/ParticipantLogin.js

https://freshworks.atlassian.net/browse/HCAP-972
- Logging in with no submitted PEOIs displays the disabled form screen
- Reuse email submission form on Participant Login screen (design signed off by Kendall)

HCAP-972 | Participant Login + Landing updates

---

client/src/pages/public/ParticipantForm.js

https://freshworks.atlassian.net/browse/HCAP-988

HCAP-988 | Remove check for disabling form

---

client/src/components/participant-form/DisabledLanding.js

This was keeping me up last night, I really wanted to simplify the layout here and make it easier to work with in the future, effect is 90% the same but we don't have to use absolute positioning now

HCAP-971 | Grid instead of absolute

---

client/src/components/participant-form/EmailSubmissionForm.js
server/db/schema.js
server/migrations/1637017368932_capture-waitlist-emails.js
server/routes/participant.js
server/services/participants.js
server/services/waitlist.js
server/validation.js

Added a new table, waitlist to capture emails. 
Added new route to add emails to the waitlist.

Hcap 973 capture emails

---

client/src/components/employer-form/BeforeYouBegin.js

Ticket: [HCAP-991](https://freshworks.atlassian.net/browse/HCAP-991)

HCAP-991 | Copy change for Employer EOI 'Before You Begin' page

---

client/src/pages/private/ParticipantEOI.js
cypress/integration/participant-landing.spec.js

https://freshworks.atlassian.net/browse/HCAP-939

HCAP-939 | Remove PEOI header and adjust alignment

---

client/src/pages/public/ParticipantLogin.js

Last minute copy change for the portal

Added copy change

---

client/src/components/employer-form/BeforeYouBegin.js

[HCAP-1003](https://freshworks.atlassian.net/browse/HCAP-1003)

HCAP-1003: Change Copy

---

client/src/pages/public/ParticipantForm.js
client/src/pages/public/ParticipantLogin.js
server/routes/participant.js

HCAP - 997 Re added form and re-enabled the form submit route

---

client/src/pages/private/ParticipantLanding.js
client/src/pages/public/ParticipantConfirmation.js
server/services/participants.js

Ticket: [HCAP-1001](https://freshworks.atlassian.net/browse/HCAP-1001)
Fix bug attached to [HCAP-1000](https://freshworks.atlassian.net/browse/HCAP-1000)

HCAP-1001: Copy Change | History bug fix

---

client/src/components/fields/RenderCheckboxGroup.js
client/src/components/participant-form/Fields.js
client/src/components/participant-form/index.js
client/src/constants/validation.js
cypress/fixtures/participant-data.json
server/tests/participant.form.test.js
server/tests/participant.landing.e2e.test.js
server/tests/participant.test.js
server/validation.js

HCAP - 992  Added "How did you find out question" to form

---

client/src/components/participant-form/Fields.js

Hide 'How did you find out about HCAP' response in participant view if the user has not answered it.

HCAP-992 Hide question on edit page if response is empty

---

.github/workflows/build.yml

HCAP-1009 | Build image and deploy to dev on update of master branch

---

client/src/pages/private/ParticipantTable.js

https://freshworks.atlassian.net/browse/HCAP-1016

HCAP-1016 | Give the ParticipantTable component a name

---

client/src/pages/private/ParticipantTable.js

https://freshworks.atlassian.net/browse/HCAP-1017

HCAP-1017 | Remove extraneous useEffect for lastNameAndEmailFilter

---

client/src/pages/private/ParticipantTable.js

https://freshworks.atlassian.net/browse/HCAP-1018

HCAP-1018 | Extract role booleans into variables 

---

client/src/components/modal-forms/ArchiveHiredParticipantForm.js
client/src/components/modal-forms/EditParticipantForm.js
client/src/components/modal-forms/HireForm.js
client/src/components/modal-forms/NewParticipantForm.js
client/src/pages/private/ParticipantTable.js

https://freshworks.atlassian.net/browse/HCAP-1019

HCAP-1019 | Refactor participant table forms

---

client/src/components/generic/Tabs.js
client/src/components/generic/index.js
client/src/components/participant-details/psi-cohort.js
client/src/pages/private/ParticipantTable.js
client/src/pages/private/ParticipantView.js
client/src/pages/private/SiteParticipantsTable.js

https://freshworks.atlassian.net/browse/HCAP-1020

HCAP-1020 | Extract CustomTabs component

---

client/src/pages/private/ParticipantTable.js
client/src/pages/private/ParticipantTableFilters.js

https://freshworks.atlassian.net/browse/HCAP-1021

HCAP-1021 | Extract ParticipantTableFilter component

---

client/src/components/generic/DebounceTextField.js
client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTable.js
client/src/pages/private/ParticipantTableFilters.js
client/src/providers/ParticipantsContext.js

https://freshworks.atlassian.net/browse/HCAP-1022

HCAP-1022 | Merge local and context reducers

---

client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTable.js
client/src/pages/private/ParticipantTableDialogues.js
client/src/pages/private/ParticipantTableFilters.js
client/src/services/participant.js

https://freshworks.atlassian.net/browse/HCAP-1024

HCAP-1024 | Refactor fetch participants

---

client/src/pages/private/ParticipantTable.js
client/src/pages/private/ParticipantTableDialogues.js
client/src/services/participant.js

https://freshworks.atlassian.net/browse/HCAP-1025

HCAP-1025 | Move API calls to service

---

client/src/components/modal-forms/EditParticipantForm.js
client/src/pages/private/ParticipantDetailsView.js

It looks like we were trying to call an undefined submissionCallback function. 
I added a check to ensure it exists. I also added a fetch data call to the onClose function for the EditParticipant component in the ParticipantDetailsView to load the updated data after it's submitted.

HCAP - 1245 Fixed callback issue with edit participant component

---

.gitignore
.prettierignore
server/.eslintrc
server/db/schema.js
server/services/participants.js
server/services/post-hire-flow.js
server/tests/participant.service.test.js
server/tests/post-hire-flow.service.test.js
server/validation.js

- Create service module with create and getter 
- Update existing `getParticipants` to include post-hire-statuses in response 
- Add and update tests.

HCAP-1047 | HCAP-1030 | Create Service for Post Hire Flow and Update existing services.

---

.docker/keycloak/users.json
docker-compose.dev.yml
server/routes/index.js
server/routes/post-hire-status.js
server/tests/participant-post-hire-status.e2e.test.js
server/tests/util/integrationTestData.js
server/tests/util/keycloak.js
server/validation.js

- Create api endpoint to create post-hire-status with tests
- Create api endpoint to get post-hire-status for a given participant with tests.

HCAP-1049 | HCAP-1030 | Add restful web api to interact with post-hire-status

---

client/src/constants/index.js
client/src/constants/postHireConstants.js
client/src/constants/validation.js
client/src/pages/private/ParticipantDetailsView.js
client/src/services/participant.js

HCAP-1051 | HCAP-1030 | Graduation Status | Frontend api integration 

---

client/src/components/modal-forms/ManageGraduationForm.js
client/src/components/participant-details/psi-cohort.js
client/src/components/participant-details/track-graduation.js
client/src/constants/validation.js
client/src/pages/private/ParticipantDetailsView.js
client/src/services/participant.js

Completed modal workflow success case 
I also added a call to fetch data after submission to get the updated data. 
I have blocked off submit for the failed cohort workflow for now.

Hcap 1050 track graduation modal

---

client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTable.js
client/src/services/participant.js
cypress/fixtures/participantTableTabs.json
server/services/participants.js
server/tests/participant.service.test.js

HCAP-1052 | HCAP-1030 | Show graduation completion status on participant list view

---

client/src/components/modal-forms/ArchiveHiredParticipantForm.js
client/src/constants/archiveParticipantsConstants.js
server/validation.js

HCAP-1055 | Text Change: `Failed cohort...` to `Unsuccessful cohort...` for Archive Reason

---

client/src/services/participant.js
server/services/participants.js
server/validation.js

Added post hired status of 'failed_cohort' on participant withdrawal.

Hcap 1031 task for failed workflow

---

client/src/components/participant-details/psi-cohort.js

Added proper event listener for route history changes.

HCAP-1081 | User proper listener of route change event

---

server/services/participants.js

HCAP-1033 | HCAP-192 | BugFix | Fix `undefined` display issue for withdrawn candidate

---

server/routes/cohorts.js
server/routes/psi-cohorts.js
server/services/cohorts.js
server/tests/cohorts.e2e.test.js
server/validation.js

HCAP-819 | Web-API | Add new patch method to update cohort

---

client/src/components/modal-forms/CohortForm.js
client/src/components/modal-forms/index.js
client/src/pages/private/CohortTable.js
client/src/pages/private/PSIView.js
client/src/pages/private/PSIViewDetails.js
client/src/services/psi-cohort.js
cypress/integration/psiDetailView.spec.js

----
- Refactor UI to sync with other views
- Integrate service layer
- Update Cohort form to support Edit
- Add success message for add/edit cohort.

HCAP-819 | Web | Edit Cohort 

---

client/src/components/fields/RenderRadioGroup.js
client/src/components/modal-forms/ManageGraduationForm.js
client/src/components/participant-details/track-graduation.js

-----
- Prepopulate graduation date with cohort end date
- Disable date picker for graduation end date

HCAP-1068 | Use Cohort end date as graduation date

---

client/src/constants/routes.js
client/src/pages/private/ParticipantDetailsView.js
client/src/pages/private/ParticipantTable.js
client/src/pages/private/SiteParticipantsTable.js
cypress/integration/editParticipant.spec.js

--------
- Add pageId url info while loading participant details page.
- From SiteView adding site id as page id
- From ParticipantView adding none as page id
- Use page id to navigate back proper site view
Ticket: [HCAP-1054](https://freshworks.atlassian.net/browse/HCAP-1054)

HCAP-1054 | BugFix | Add stateful navigation

---

client/src/components/modal-forms/CohortForm.js
client/src/pages/private/PSIViewDetails.js

----
Showing Field Validation Error for updating cohort size if new size is less than current allocation
Ticket: [HCAP-1095](https://freshworks.atlassian.net/browse/HCAP-1095)

HCAP-1095 | HCAP-819 | BugFix | Showing error on update of cohort size

---

client/src/components/modal-forms/ManageGraduationForm.js
client/src/components/participant-details/track-graduation.js
client/src/constants/validation.js
server/validation.js

----
- Showing warning message on Unsuccessful participant with continue No
Ticket: [HCAP-1097](https://freshworks.atlassian.net/browse/HCAP-1097)

HCAP-1097 | BugFix | Show warning message on Unsuccessful cohort participant 

---

client/src/components/modal-forms/ManageGraduationForm.js

Ticket: [HCAP-1098](https://freshworks.atlassian.net/browse/HCAP-1098)

HCAP-1098 | BugFix | Disabling Update Graduation Status for before cohort end

---

client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTable.js
client/src/utils/prettifyStatus.js
cypress/fixtures/participantTableTabs.json
server/constants/validation-constants.js
server/services/participants-helper.js
server/services/participants.js

HCAP-1073 | RoS | FrontEnd + Backend | RoS tab with archive button

---

README.md
server/db/schema.js
server/migrations/1648216369918_create-audit-table.js
server/services/cohorts.js
server/services/participants.js
server/tests/cohort.service.test.js
server/tests/post-hire-flow.service.test.js
server/tests/util/integrationTestData.js
server/tests/util/testData.js

HCAP-1116 | OpsReq | Change Cohort Service method

---

.github/workflows/service.run.dev.yml
.github/workflows/service.run.prod.yml
.github/workflows/service.run.test.yml
Makefile
docker-compose.dev.yml
openshift/service.pod.yml
server/scripts/cli.js

HCAP-1116 | Pod | Create resource to execute service req in OpenShift

---

client/src/pages/private/UserView.js
server/keycloak.js
server/migrations/1648754857650_sync-user-with-kc.js
server/nodemon.json
server/routes/index.js
server/routes/user.js
server/services/sync-user.js
server/services/user.js
server/tests/util/db.js
server/validators/employer-operation.js

HCAP-1143 | Show User Info |  Store user details in db

---

client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTable.js
cypress/fixtures/participantTableTabs.json
server/services/participants-helper.js

Displaying employer details for Hired status

HCAP-1143 | View Hired By column Under `Hired Participant` tab

---

server/constants/validation-constants.js
server/services/participants-helper.js

HCAP-1143 | HCAP-1152 | Sort Employer name column

---

client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTable.js
client/src/services/participant.js
client/src/utils/prettifyStatus.js
server/package-lock.json
server/routes/participant.js
server/services/participants-helper.js
server/services/participants.js

HCAP-1156 | Archive with Multi Org Support

---

client/src/pages/private/Admin.js
client/src/pages/private/ParticipantTable.js
client/src/utils/misc.js

https://freshworks.atlassian.net/browse/HCAP-1155
🐛 **bug description**: long names are not truncated when displayed on employer portal causing UI issues
🔧 **possible fixes**: 
1. Add `maxWidth` to `Typography` and display the rest as `...`
❓ do we want to make it consistent across the application in this case? Possibly create a new component?
2. Specify `maxLength` to user `auth.user.name` instead
This PR implements 1st option
Open for discussion 🙂

HCAP-1155: minor style updates to Typography

---

client/src/pages/private/Admin.js
client/src/pages/private/ParticipantTable.js

https://freshworks.atlassian.net/browse/HCAP-1155
Follow-up PR to improve ellipsis mask:
- adding `className` prop to `Typography` 👀 
- updating `maxLength` to 20 characters

HCAP-1155: followup PR for employer name mask

---

documents/tds/multi-org-support.md
documents/tds/post-hire-workflow.md
server/db/schema.js
server/migrations/1649795536386_create-site-participants-status-table.js
server/tests/participant-status.test.js
server/tests/util/integrationTestData.js

HCAP-1107/1167 | MultiOrg | Prospecting-site | Create db table

---

client/src/components/fields/RenderMultiSelectField.js
client/src/components/generic/Dialog.js
client/src/components/modal-forms/ProspectingForm.js
client/src/components/modal-forms/SelectProspectingSiteForm.js
client/src/components/modal-forms/index.js
client/src/constants/participantTableConstants.js
client/src/constants/theme.js
client/src/constants/validation/schema/index.js
client/src/constants/validation/schema/schema-select-prospecting-sites.js
client/src/pages/private/ParticipantTable.js
client/src/pages/private/ParticipantTableDialogues.js
client/src/utils/getDialogTitle.js

https://freshworks.atlassian.net/browse/HCAP-1164
Added a new modal for Participant Table. This modal appears when somebody is trying to Engage a participant
made some updates to `DialogTitle` as well - let me know what you think
This is a subtask for HCAP-1107
Adding some updates to `Prospecting Confirmation` as well to match designs
https://www.figma.com/proto/35c5C0DyTEOxJ4N4DIaADL/HCAP-Design?node-id=2002%3A19657&viewport=241%2C48%2C0.36&scaling=min-zoom&starting-point-node-id=2002%3A19657
_Note_: this is for single participant only

HCAP-1164: Select Site modal

---

client/src/components/modal-forms/SelectProspectingSiteForm.js
client/src/pages/private/ParticipantTableDialogues.js
client/src/services/participant.js

Ticket: HCAP - [1107](https://freshworks.atlassian.net/browse/HCAP-1107)/[1173](https://freshworks.atlassian.net/browse/HCAP-1173)

HCAP-1107/1173 | Frontend integration with updated web api

---

client/src/pages/private/ParticipantView.js

Description of problem (and chosen solution): https://freshworks.atlassian.net/browse/HCAP-1162
Put horizontal scroll on overflowing container element

HCAP-1162 | Fix header alignment

---

client/src/pages/private/Admin.js
client/src/pages/private/ParticipantTable.js

https://freshworks.atlassian.net/browse/HCAP-1155
Just increasing max character length for names

HCAP-1155: adding maxLength for employers name

---

client/src/components/generic/Table.js
client/src/components/generic/Tabs.js
client/src/pages/private/ParticipantTable.js
cypress/fixtures/participantTableTabs.json
cypress/integration/participantTable.spec.js

https://freshworks.atlassian.net/browse/HCAP-1172
**What's included in this PR**:
- checkboxes to select rows ✅ 
- `Bulk Engage` button 
- minor improvements to `ParticipantTable` 🖌️ 
_Note_: there's a follow up PR to add `Select Site` modal; keeping things small and easy to review 👀 🙂

HCAP-1172: table multi-select functionality

---

server/services/participants-helper.js
server/tests/participant-status.test.js

This PR will fix the participant's dual visibility issue for **Available Participants** and **My Candidate** views.

HCAP-1140: Fix available participant view issue

---

client/src/components/generic/Dialog.js
client/src/components/generic/Table.js
client/src/components/modal-forms/ProspectingForm.js
client/src/components/modal-forms/SelectProspectingSiteForm.js
client/src/constants/participantTableConstants.js
client/src/constants/theme.js
client/src/pages/private/ParticipantTable.js
client/src/pages/private/ParticipantTableDialogues.js
client/src/utils/getDialogTitle.js

https://freshworks.atlassian.net/browse/HCAP-1172
**What's included in this PR?** 👀
- minor improvements to Dialog component
- changes to avoid horizontal scroll-bar within a modal
- adding some logic to SelectSite modal for mutli-participant flow
- adding ellipsis mask for loooong site names
- updates to ProspectingForm to support multi-select
- multiSelect with pagination
- rows are selected across different pages
_Muti Engage:_
_Pagination:_
https://www.figma.com/proto/35c5C0DyTEOxJ4N4DIaADL/HCAP-Design?node-id=2005%3A20369&viewport=241%2C48%2C0.36&scaling=min-zoom&starting-point-node-id=2002%3A19657

HCAP-1172: bulk engage SelectSite modal

---

client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTable.js
cypress/fixtures/participantTableTabs.json

https://freshworks.atlassian.net/browse/HCAP-1106?atlOrigin=eyJpIjoiYjJlYmE0MDU0ZTQ4NGZiNDgwYTAzODI0NGZhZjZmODMiLCJwIjoiaiJ9
Last Engaged By column is between Last Updated and Actions columns.
Not yet sortable

HCAP-1106 | Show last engaged by column

---

server/routes/participant.js
server/services/participants.js
server/tests/employer-action.e2e.test.js
server/tests/participant-status.test.js
server/validation.js
server/validators/bulk-engage.js
server/validators/index.js

Ticket: [HCAP-1114](https://freshworks.atlassian.net/browse/HCAP-1114)

HCAP-1114/1179 | Bulk engage api and service creation

---

server/package-lock.json
server/package.json
server/services/participants.js

For Multi-Org reject (Archive from **My Candidate**), implementing as user-specific reject.

HCAP-1140 | Manage Reject Status for Multi Org

---

Makefile

Added one dry run cmd to verify mongo-backup deployment config.

HCAP-1150 : Add make alias to dry run mongo backup config

---

client/src/pages/private/ParticipantTable.js

Showing the correct Acknowledgement Button for a participant with ROS status in the `My Candidate` tab in case of hired by peer scenario. 
Ticket: [HCAP-1187](https://freshworks.atlassian.net/browse/HCAP-1187)

HCAP-1187 | BugFix | Showing `ack` on `ros` status

---

client/src/pages/private/ParticipantTable.js

https://freshworks.atlassian.net/browse/HCAP-701
Updating count to show how many employers are engaging a particular participant

HCAP-701: incorrect In Progress status bug

---

client/src/components/modal-forms/SelectProspectingSiteForm.js
client/src/pages/private/ParticipantTable.js
client/src/services/participant.js
cypress/integration/participantTable.spec.js
server/constants/participant-status.js
server/db/db.js
server/logger.js
server/routes/participant.js
server/services/feature-flags.js
server/services/participant-status.js
server/services/participants.js
server/tests/employer.form.test.js
server/tests/employer.site.test.js
server/tests/participant-status.test.js
server/tests/participant.service.test.js
server/tests/util/db.js
server/validators/participant.js

HCAP-1140 | Enable feature flag | Update backend to support single site prospecting

---

client/src/components/generic/Page.js
client/src/components/modal-forms/NewSiteForm.js
client/src/pages/private/SiteTable.js
client/src/pages/private/SiteView.js
server/routes/milestone-report.js
server/services/reporting.js
server/tests/milestone-report.e2e.test.js

https://freshworks.atlassian.net/browse/HCAP-1014
❔ **What's included:** 🎉 
- general refactoring to match current designs 🎨 
- generating report based on health region for both HA and MoH
- downloading report
https://www.figma.com/file/35c5C0DyTEOxJ4N4DIaADL/HCAP-Design
**HA:**

HCAP-1014: HA CSV hiring report by health region

---

Makefile
server/keycloak.js
server/routes/participant-user.js

HCAP-1191 | TryFix | Security alerts | Fix tagging alias issue in Makefile

---

client/src/components/generic/Table.js
client/src/pages/private/ParticipantTable.js

https://freshworks.atlassian.net/jira/software/c/projects/MOH/boards/244?modal=detail&selectedIssue=HCAP-1208
Decided to scope the multiselect to the current page, so that:
- selecting all selects all items on page
- changing page deselects selection
- the select all checkbox is displayed as checked when all the items on the page are selected

HCAP-1208 | Multiselect on multiple pages

---

server/routes/participant-user.js
server/routes/user.js

HCAP-1191 | Security Alert Fix | Add validation and sanitization on user input

---

client/src/pages/private/SiteParticipantsTable.js
client/src/pages/private/SiteViewDetails.js
client/src/providers/SiteDetailTabContext.js
server/routes/employer-sites.js

Ticket: https://freshworks.atlassian.net/browse/HCAP-921
In the table's handleArchive I took out the call to forceReload and replaced it with a call to fetch the site's data and dispatch the site's new status through context provider. This was the only reference to forceReload, so I got rid of it, and the onArchiveParticipantAction prop. Stale wasn't used anymore either so I got rid of it, and the 2/3 extremely similar useEffect calls. Was getting dependency complaints from React compiler, got rid of those two (by supplying the dependencies).

HCAP-921 |  Positions overview count

---

client/src/components/generic/Table.js
client/src/components/modal-forms/ProspectingForm.js
client/src/pages/private/ParticipantTableDialogues.js

https://freshworks.atlassian.net/browse/HCAP-1223
❓**What's included:** 🎉 
- `Bulk engage` button is now active when only 1 participant is selected
- If 1 participant engaged --> the confirmation modal says `${name} has been engaged`
- If 2+ participants engaged -->  the confirmation modal says `${number} participants have been engaged`

HCAP-1223: fixing bulk engage for multi-select

---

client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTable.js
client/src/services/participant.js
client/src/utils/gen-util.js
client/src/utils/prettifyStatus.js
cypress/fixtures/participantTableTabs.json
server/constants/participant-status.js
server/routes/participant.js
server/services/participant-status.js
server/services/participants-helper.js
server/tests/participant-status.test.js

HCAP-1166 | Multi-org | Reject behaviour

---

client/src/components/modal-forms/ArchiveHiredParticipantForm.js

Ticket: https://freshworks.atlassian.net/browse/HCAP-1219
This one too: https://freshworks.atlassian.net/browse/HCAP-1220
Forced the form to not consider the other fields on the form touched after changing type in select box.

HCAP-1219 | Validation Errors on Form after changing type field

---

Makefile
server/migrations/1653661929058_update-ros-table.js
server/migrations/1653662298756_validate-latest-ros-participant-entry.js
server/routes/employer-sites.js
server/routes/return-of-service.js
server/services/employers.js
server/services/return-of-service.js
server/tests/return-of-service.e2e.test.js
server/tests/return-of-service.test.js
server/validators/return-of-service.js

HCAP-1084 | Backend | Add is_current col migration | Update service methods and rest api

---

client/src/components/fields/RenderSelectField.js
client/src/components/fields/RenderTextField.js
client/src/components/modal-forms/ReturnOfServiceForm.js
client/src/constants/validation/schema/schema-return-of-service.js
client/src/services/return-of-service.js
client/src/utils/getDialogTitle.js
server/routes/employer-sites.js

HCAP-1084 | RoS | Different site case

---

Makefile

This is a small PR to add a `make` alias to deploy the current `prod` tag to any specified env

HCAP-1226 | Makefile/devops | Create alias to deploy prod tag to specific env

---

client/src/constants/participantTableConstants.js
cypress/fixtures/participantTableTabs.json

Update Column name label and test fixtures.

HCAP-1084 | UI | Update Display label of `RoS Site` name

---

server/routes/employer-sites.js

HCAP-1084/1236 | BugFix | Allow pvt employer to access all sites basic info

---

Makefile
openshift/in-progres-stale-clean.cronjob.yml
server/scripts/clean-up.js
server/services/clean-up.js

HCAP-1216 | Cronjob |  Infra code

---

Makefile
server/services/clean-up.js

HCAP-1216 | Stale status clean CronJob

---

client/package-lock.json

https://github.com/bcgov/hcap/security/dependabot
We have a few dependabot alters; one marked as Critical
This PR resolves alert in `package/client`
_Note_: we need to figure out what to do about `dicer` [vulnerability](https://github.com/bcgov/hcap/security/dependabot/71)

HCAP: dependabot alerts

---

client/src/utils/prettifyStatus.js

https://freshworks.atlassian.net/browse/HCAP-1226
Adding some more checks to render `In Progress` statuses for MoH
The issue might not be in the codebase; need to check in prod

HCAP-1226: In Progress status for MoH

---

openshift/in-progres-stale-clean.cronjob.yml

HCAP-1216 | Testing | Cronjob and clean-up service

---

client/src/pages/private/ParticipantDetailsView.js
client/src/services/participant.js
cypress/integration/editParticipant.spec.js
server/routes/participant.js
server/services/participant-details.js
server/tests/participant-details.e2e.test.js

HCAP-1074 / HCAP-1079| Backend + Front end | Display RoS info on Participant details page

---

server/services/post-secondary-institutes.js
server/services/user.js

HCAP-1198 / 1248 | Backend | BugFix | Sort institute name | Fix notification bug

---

client/src/pages/private/ParticipantTable.js

https://freshworks.atlassian.net/browse/HCAP-1245
Just adding a `dispatch` action to update notification as per wonderful [comment](https://freshworks.atlassian.net/browse/HCAP-1245?focusedCommentId=59652) made by @taraepp 🎉

HCAP-1245: RoS End of Service bug fix

---

client/src/pages/private/PSITable.js
client/src/pages/private/PSIView.js
client/src/pages/private/ReportingView.js
cypress/integration/psiDetailView.spec.js
cypress/integration/psiView.spec.js
server/routes/index.js
server/routes/milestone-report.js
server/routes/psi-report.js
server/services/reporting.js

https://freshworks.atlassian.net/browse/HCAP-1037
Adding in a new option for HA and MoH to download _'Participants attending PSIs'_ report

HCAP-1037: participants attending PSI report 

---

client/src/assets/images/arrow-right-icon.svg
client/src/constants/misc.js
client/src/pages/public/EmployerLogin.js

Making some changes according to the designs: https://www.figma.com/file/35c5C0DyTEOxJ4N4DIaADL/HCAP-Design?node-id=2560%3A36135

HCAP-1237: login form FE updates

---

client/src/constants/misc.js

https://freshworks.atlassian.net/browse/HCAP-1237
Adding prod link based on the discussion

HCAP-1237: PEOI link

---

server/constants/milestone-report-type.js
server/services/reporting.js

https://freshworks.atlassian.net/browse/HCAP-1254
Updating the logic based on the [discussion](https://freshworks.slack.com/archives/C011G18PW5S/p1656448711903019) + including `archived` participants

HCAP-1254: PSI report updates

---

client/src/components/modal-forms/PSIForm.js
client/src/components/modal-forms/index.js
client/src/pages/private/PSIView.js
client/src/pages/private/PSIViewDetails.js
client/src/services/psi-cohort.js
cypress/integration/psiDetailView.spec.js
server/routes/post-secondary-institutes.js
server/services/post-secondary-institutes.js
server/tests/psi.e2e.test.js
server/tests/psi.service.test.js
server/tests/util/integrationTestData.js

HCAP-1200 | api | Add new service and end-point | ui | Refactor PSI form

---

client/src/pages/private/PSIView.js
client/src/pages/public/EmployerLogin.js
cypress/integration/psiDetailView.spec.js

HCAP-1237/bug-fix/1256 | Fix copy issue

---

client/src/components/employer-form/BeforeYouBegin.js
client/src/components/employer-form/CollectionNotice.js
client/src/components/participant-form/DisabledLanding.js
client/src/components/participant-form/Fields.js
client/src/components/participant-form/Summary.js
client/src/constants/index.js
client/src/constants/links.js
client/src/constants/misc.js
client/src/pages/private/ParticipantFullWithdrawPage.js
client/src/pages/private/ParticipantLandingEmpty.js
client/src/pages/public/EmployerLogin.js
client/src/pages/public/LoginFooter.js
client/src/pages/public/ParticipantLogin.js

https://freshworks.atlassian.net/browse/HCAP-1257
Just adding a few links for the footer

HCAP-1257: footer links

---

client/src/constants/links.js

https://freshworks.atlassian.net/browse/HCAP-1260
Just a quick fix for copyright link

HCAP-1260: footer copyright link

---

server/routes/milestone-report.js
server/services/reporting.js

https://freshworks.atlassian.net/browse/HCAP-1230
Updating RoS and Hiring reports to include _first and last names_

HCAP-1230: Add First Name and Last Name to Reports

---

client/src/pages/public/ParticipantConfirmation.js

https://freshworks.atlassian.net/browse/HCAP-1201
Some minor text changes to the confirmation page + refactoring 🎨

HCAP-1201: changes to PEOI confirmation page

---

client/src/components/modal-forms/ChangeSiteForm.js
client/src/pages/private/ParticipantTableDialogues.js

https://freshworks.atlassian.net/browse/HCAP-1263
🔧🪲 Bugfix for 1076: show a list of all available sites instead of employer specific for HA

HCAP-1263: bugfix for Change RoS site

---

client/src/components/modal-forms/ChangeSiteForm.js
client/src/constants/validation/schema/schema-change-ros-site.js
client/src/pages/private/ParticipantTableDialogues.js
client/src/services/return-of-service.js
server/routes/return-of-service.js
server/services/return-of-service.js
server/validators/return-of-service.js

https://freshworks.atlassian.net/browse/HCAP-1264
🔧🪲 **Bugfix for 1076**: updating the logic so that ROS Start date is not affected by the site change

HCAP-1264: RoS start date fix

---

client/src/components/fields/RenderAutocomplete.js
client/src/components/modal-forms/ChangeSiteForm.js
client/src/constants/validation/schema/schema-change-ros-site.js
client/src/pages/private/ParticipantTableDialogues.js

https://freshworks.atlassian.net/browse/HCAP-1267
Some tweaks to allow `healthAuthority` field auto-populate based on the Site selected

HCAP-1267: Health Authority value select fix

---

client/src/pages/private/ParticipantTable.js
server/services/reporting.js

https://freshworks.atlassian.net/browse/HCAP-1268
When generating a RoS report as MoH, `Start Date at a Site` didn't reflect the changes.
This PR is to fix this issue ☝️

HCAP-1268: fixing Start Date at a Site for MoH reports

---

server/services/participants-helper.js

https://freshworks.atlassian.net/browse/HCAP-1266
Adding sorting for `Last engaged Date` column

HCAP-1266: lastEngagedDate sorting fix

---

client/src/pages/private/ParticipantTable.js
server/routes/participant.js
server/services/feature-flags.js

Ticket: https://freshworks.atlassian.net/browse/HCAP-1269
Removal of the feature flag use for multi org prospecting across backend/frontend

fix: removing the use of feature flags for multi org prospecting

---

client/src/constants/healthAuthorities.js
client/src/pages/private/EOIView.js
client/src/pages/private/ParticipantView.js
client/src/pages/private/SiteTable.js
cypress/fixtures/participantTableTabs.json
cypress/integration/participantView.spec.js

https://freshworks.atlassian.net/browse/HCAP-182
Updating user permissions to view `My Sites` tab + some minor refactoring to `constants` file

HCAP-182: view only sites associated with user for HAs

---

server/services/participants-helper.js

https://freshworks.atlassian.net/browse/HCAP-1265
Currently deployed to dev + test, quick tests suggest this works
https://freshworks.slack.com/archives/C011G18PW5S/p1658784244918919?thread_ts=1658780969.860779&cid=C011G18PW5S

HCAP-1265 hired ros pagination

---

server/services/user.js

https://freshworks.atlassian.net/browse/HCAP-1275
We need to update the query to search for ROS count after introducing the _Change Site_ functionality (https://github.com/bcgov/hcap/pull/759)
This PR is to unblock release

HCAP-1275: fixing ROS count banner for HA

---

cypress/integration/psiDetailView.spec.js

- I don't think we need to disable waiting for actionability here, this could be a reason why inputs are missed occasionally

HCAP-1289 Don't force clicks

---

README.md

Describe the process for adding certs to dev and test routers on openshift

HCAP-1291 Add instructions for generating SSL for dev/test

---

client/public/index.html

- Add opengraph, twitter tags to enable link unfurling + additional SEO metadata
https://freshworks.atlassian.net/browse/HCAP-534

HCAP-534 Add SEO description meta tags

---

client/src/components/generic/Table.js
client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTable.js
client/src/pages/private/ParticipantTableFilters.js
client/src/providers/ParticipantsContext.js
client/src/services/participant.js
cypress/integration/participantTable.spec.js
server/routes/participant.js

Ticket: https://freshworks.atlassian.net/browse/HCAP-1060
- used the MUI TablePagination in Table component (should be reusable for other tables) 
- moved the pageSize variable from constants into ParticipantsContext

HCAP-1060 | Participants per page dropdown

---

client/src/pages/private/PSIViewDetails.js
client/src/pages/private/ParticipantDetailsView.js
client/src/pages/private/SiteViewDetails.js

https://freshworks.atlassian.net/browse/HCAP-1302
Adding `minWidth` value to prevent pages from shrinking based on content

HCAP-1302: page width bug fix

---

.dockerignore
.github/workflows/test.yml
Makefile

https://freshworks.atlassian.net/browse/HCAP-1128

HCAP-1128 cache docker

---

.dockerignore
.github/workflows/format.yml
.github/workflows/sonar.yml
.github/workflows/test.yml
Makefile

https://freshworks.atlassian.net/browse/HCAP-1128

HCAP-1128 general improvements

---

server/services/participants-helper.js

https://freshworks.atlassian.net/browse/HCAP-1303

HCAP-1303 My Candidates: don't return ROS + Archived participants

---

server/services/participants-helper.js

http://hcapemployers.local.freshworks.club:4000/
We learned that ROS site is not what determines if an HA can see a participant or not, but more the hiring site.
This will conflict with Tara's PR

fix: use hiring site to determine permissions for ros status

---

client/package-lock.json
client/src/pages/private/ParticipantUpload.js
package-lock.json
server/package-lock.json
server/package.json
server/routes/participant.js
server/tests/participant.test.js

This reverts commit 092454feb778c53a6dea825ffeebaef29abde3f3

Revert "HCAP: dependabot alerts (#819)"

---

server/routes/cohorts.js
server/routes/participant.js
server/routes/post-hire-status.js
server/routes/return-of-service.js
server/scripts/services/change-cohort.js
server/services/participant-status.js
server/services/participants.js
server/services/user-validation.js
server/tests/participant.service.test.js

Some very strange logic with `getParticipantById` where it was accepting an object of a certain way, but there were about three different ways it was called.

fix: Fixing whatever was up with getParticipantById

---

client/src/pages/private/SiteTable.js

https://freshworks.atlassian.net/browse/HCAP-1315

HCAP-1315 Add site's city to SiteTable

---

client/src/pages/private/SiteTable.js
server/services/employers.js

https://freshworks.atlassian.net/browse/HCAP-376
- Rewrote the sites query because `fields` causes a lot of unexpected issues within MassiveJS
- Add "Hires" column to sites table

HCAP-376 Show Site Hires

---

cypress/integration/participantStatus.spec.js

Ticket: https://freshworks.atlassian.net/browse/HCAP-1342
The bug itself is taken care of by https://github.com/bcgov/hcap/pull/833, this is some automated testing that should help us catch similar issues in the future. Takes a participant through a complete flow (originally written for a different bug), and has some functions that can be reused for different flows.

HCAP-1342 | Adding automated testing for hire flow

---

client/src/pages/private/CohortDetails.js
client/src/pages/private/CohortTable.js
client/src/services/participant.js
client/src/services/psi-cohort.js
server/routes/cohorts.js
server/services/cohorts.js

https://freshworks.atlassian.net/browse/HCAP-1056
This request is for addressing some comments for https://github.com/bcgov/hcap/pull/830 + adding a participant table for cohort view

HCAP-1056: cohort participants list

---

client/src/pages/private/SiteTable.js
client/src/pages/private/SiteViewDetailsTabs.js
cypress/integration/participantStatus.spec.js
server/services/employers.js
server/tests/employer.site.e2e.test.js
server/tests/employer.site.test.js

https://freshworks.atlassian.net/browse/HCAP-376
- Rewrote the sites query because fields causes a lot of unexpected issues within MassiveJS
- Add "Hires" column to sites table

HCAP-376 Available participants for My Sites

---

client/src/pages/private/UserView.js
client/src/services/return-of-service.js
client/src/services/site.js
server/routes/employer-sites.js
server/services/employers.js
server/tests/employer.site.e2e.test.js

Ticket: https://freshworks.atlassian.net/browse/HCAP-1338
- added back in a function to get all sites
- made it its own endpoint this time though

HCAP-1338 | RoS and Change Site does not show whole sites list

---

server/services/employers.js

https://freshworks.atlassian.net/browse/HCAP-1341

HCAP-1341 Add ordering to getAllSites

---

client/src/pages/private/SiteTable.js
client/src/services/site.js
server/routes/employer-sites.js
server/services/employers.js

Add a query on the endpoint to be able to get regions, and separate the region specific query.
I'm sorry that I couldn't avoid a flag, but I am trying to limit it to an extent!
https://freshworks.atlassian.net/browse/HCAP-1337

Hcap 1337 region sites

---

client/src/pages/private/CohortDetails.js

https://freshworks.atlassian.net/browse/HCAP-1344
This request is for adding some extra checks when rending the participant table

HCAP-1344: bug fix for the Cohort details page

---

client/src/pages/private/CohortTable.js
client/src/pages/private/EOIView.js
client/src/pages/private/PSITable.js
client/src/pages/private/SiteTable.js
client/src/pages/private/SiteViewDetailsTabs.js
client/src/pages/private/UserView.js
client/src/utils/gen-util.js

Ticket: https://freshworks.atlassian.net/browse/HCAP-1347
- issue caused by lodash _orderBy function in FE
- made a util function to deal with it
- I replaced the function in ONE place with a new one (ie: to deal with the bug)
- but a search for _orderBy shows it being used in 8 different files, probably causing the same issue there

HCAP-1347 | Sort order on sites table

---

server/services/employers.js

I missed filtering duplicate participants, I moved from a join to a subquery to properly count hires. The subquery is modeled after https://github.com/bcgov/hcap/blob/dev/server/services/employers.js#L130
https://freshworks.atlassian.net/browse/HCAP-1345

HCAP-1345 Add subquery to skip counting duplicate participants

---

client/src/utils/gen-util.js

Ticket: https://freshworks.atlassian.net/browse/HCAP-1352
Chose to treat nulls like empty string, as that should be consistent for user.

HCAP-1352 | Nulls breaking sort

---

client/src/pages/private/CohortTable.js
server/services/cohorts.js

https://freshworks.atlassian.net/browse/HCAP-1349
This request is for adding an extra join to select only those participants who have a status assigned to them

HCAP-1349: cohort available seats fix

---

client/.eslintrc

https://freshworks.atlassian.net/browse/HCAP-1360
So we can catch these earlier and not rely on sonarcloud

HCAP-1360 Error on unused vars

---

client/src/pages/private/CohortDetails.js
client/src/pages/private/ParticipantDetailsView.js
client/src/services/participant-details.js

https://freshworks.atlassian.net/browse/HCAP-1357
- Rework routing for the participant details component
- Add cases for cohort, properly navigate to participant details
https://user-images.githubusercontent.com/71518072/190430611-6719d111-3d32-4120-9d4b-850d18102708.mp4

HCAP-1357 Properly handle breadcrumb routing

---

README.md

[HCAP-1375](https://eydscanada.atlassian.net/browse/HCAP-1375)
This PR improves the README file with the following changes:
* Fixes typos and formatting issues
* Restructures certain information into tables
* Updates and expands upon ToC

HCAP-1375 - Readme proofreading and formatting

---

client/src/components/modal-forms/EditParticipantForm.js

https://freshworks.atlassian.net/browse/HCAP-1354
- Disabled interest field for hired participants
- Disable withdrawing in service method

HCAP-1354 remove Post-hire MOH withdrawal

---

client/src/pages/private/CohortDetails.js

[HCAP-1372](https://eydscanada.atlassian.net/browse/HCAP-1372)
This PR fixes the bug causing incorrect dates on the cohort page.

HCAP-1372: fix Start date and End date having a difference of 1 day in details Cohort page

---

docs/database.md

Ticket: [HCAP-1356](https://eydscanada.atlassian.net/browse/HCAP-1351)
This adds some documentation around restoring backups and what to do when it all goes terribly wrong. It might not be obvious what some things are without looking at Openshift, so feel free to ping me if you don't have Openshift access yet

docs: Add steps for database backup/restoration

---

.github/workflows/test.yml
client/src/components/modal-forms/PhaseDialog.js
client/src/constants/validation/schema/schema-create-phase.js
cypress/integration/phaseAllocation.spec.js
server/validators/phase.js

- Add Placeholder text to input field (going off design in ticket for text)
- Add Max character validation to form (I used 255 as the db limit, but can decrease, can update error message to anything) 
- Added validation to ensure endDate is not before or on the same day as startDate (Can update error message)

hcap 1384/hcap 1385 - phase form validations

---

client/src/pages/private/SiteViewDetailsTabs.js

- Used start_date for Hired and Allocation table
- Used withdrawnDate for Withdran hire table

HCAP-1413 update sorting for site Details tables 

---

server/routes/milestone-report.js
server/services/reporting.js

Adding Position type and employment type to pulling down the ROS report

fix: add position / employment type to ROS report

---

client/src/constants/validation/schema/schema-allocation.js
server/validators/allocation.js

Adds validation to allocation form to prevent server errors ([HCAP-1421](https://eydscanada.atlassian.net/browse/HCAP-1421)).

HCAP-1421: Limited allocation to 100k to prevent errors

---

server/services/employers.ts

- Formatted the phase start_date and end_date before returning to the FE
- Now displaying correctly on the UI

HCAP-1426 - Phase dates are displaying as a day behind

---

README.md
docs/ssl-certificates-renewal.md

Add documentation for tool being utilized to auto-renewal ssl certificates for dev and test environments

Document SSL Auto-Renewal tool

---

client/src/components/modal-forms/PhaseDialog.js

CSS Update - add bold to date range

---

client/src/components/modal-forms/BulkAllocationForm.js
client/src/pages/private/SiteTableAllocation.js
client/src/utils/gen-util.js

- Added util fn to truncate phase name,  decided to do this in JS vs CSS as I wanted the date range to be visible on the dropdown.

added util function to truncate phase name

---

client/src/constants/participantDetailsConstants.js
client/src/pages/private/ParticipantDetailsView.js
client/src/services/participant-details.js
client/src/services/participant.js
server/services/participants-helper/core.ts

Work completed:
* Added site and status to details page

HCAP-1443 MoH/HA See site that hired participant

---

client/src/constants/participantDetailsConstants.js
client/src/pages/private/ParticipantDetailsView.js
client/src/services/participant-details.js
client/src/services/participant.js
server/services/participants-helper/core.ts

This reverts commit cc9e5679d277bc75033278b49ee780748ca7cf87.
With the bug at HCAP-1473, this is better off reverted until next week!

Revert "HCAP-1443 MoH/HA See site that hired participant (#926)"

---

server/server.ts

Needed to add the new logon portal

fix: replace csp

---

client/src/pages/public/ParticipantLogin.js

- reverted `ParticipantLogin` back to use keycloak.login instead of custom url
- updated idpHint to `bcsc_hcap`

revert back to use kc login instead of custom login url

---

server/keycloak.ts

This is Cory's commit cherry picked from [the other PR](https://github.com/bcgov/hcap/pull/955)
As far as I can see, it's the only change, so this should do it.

set pending role for bceid and idir users on login check

---

.docker/keycloak/users.json

added an email to the maximus test user

fix: add email to maximus test-user

---

server/constants/index.ts
server/constants/user-roles.ts
server/keycloak.ts
server/routes/index.ts
server/scripts/cache-user-roles.ts
server/services/reporting/participants-report.ts
server/services/sync-user.ts
server/tests/user-keycloak-migration.test.ts

With no pagination, we want to ensure we avoid requesting all users. It'll be pretty big in the MoH Environment

fix: do not request all users, only specific roles

---

client/src/components/generic/Header.js

Log out redirect chain: Keycoak -> SiteMinder -> HCAP

HCAP-1486 log out of siteminder

---

server/keycloak.ts

Change the base URL of userinfo endpoint to KEYCLOAK_AUTH_URL

HCAP-1488 fix healthcheck

---

client/src/components/generic/CheckPermissions.js
cypress/integration/reportingView.spec.js
cypress/integration/siteView.spec.js

HCAP-1489 update permission denied message

---

client/src/components/modal-forms/ArchiveHiredParticipantForm.js
client/src/components/participant-form/Fields.js
client/src/components/participant-form/sections/BackgroundInformationSection.js
client/src/components/participant-form/sections/ContactInformationSection.js
client/src/components/participant-form/sections/EligibilitySection.js
client/src/components/participant-form/sections/HCAPProgramSection.js
client/src/components/participant-form/sections/MarketingSection.js
client/src/components/participant-form/sections/OtherSection.js
client/src/components/participant-form/sections/PreferredWorkLocation.js
client/src/constants/form-options.js
client/src/utils/formatOptions.js
client/src/utils/index.js

- meant to address duplicity sonar report in base branch

try to address duplicity sonar report, extract sections into components

---

client/src/components/participant-form/sections/ContactInformationSection.js
client/src/components/participant-form/sections/MarketingSection.js
client/src/components/participant-form/sections/OtherSection.js

- updates to PEOI form from meeting
- update Q13 helper text to `Please select all that apply`
- move Indigenous question and please note into `Other` section
[HCAP-1509](https://eydscanada.atlassian.net/jira/software/c/projects/HCAP/boards/206?selectedIssue=HCAP-1509)

update PEOI forms from meeting comments

---

client/src/components/participant-form/Summary.js
client/src/constants/links.js

- add temp MHAW link to EOI form
- update links text size on EOI form
[HCAP-1503](https://eydscanada.atlassian.net/jira/software/c/projects/HCAP/boards/206?selectedIssue=HCAP-1503)
[HCAP-1509](https://eydscanada.atlassian.net/jira/software/c/projects/HCAP/boards/206?selectedIssue=HCAP-1509)

update font size for training links, add temp link for MHAW

---

.docker/keycloak/users.json
client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTable.js
client/src/pages/private/ParticipantTableFilters.js
cypress/integration/participantView.spec.js
server/constants/index.ts
server/constants/mhaw-enabled-regions.ts
server/services/participants-helper/ProgramFilteredParticipantsFinder.ts
server/services/participants/participant-entries.ts
server/tests/participant.service.test.ts

- Hide disabled location and program filters
- Allow only vancouver island and interior HA and employer users to access MHAW

HCAP-1510 allow only vancouver island and interior to access MHAW

---

server/services/participant-details.ts

- updated access to participant details endpoint, will now only retrieve users based on program and employer type

HCAP-1508 - update access to participant details for mhsu and private employers endpoint

---

client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTable.js
client/src/pages/private/ParticipantTableFilters.js
server/routes/participant.ts
server/services/participants-helper/RegionsFilteredParticipantsFinder.ts
server/services/participants/participant-entries.ts

- Add another checkbox filter to allow MHSU employers to filter by people with lived/living experience
- should not be visible for MHSU Employers from Northern Health, Fraser Health and Vancouver Coastal Health,  all Private employers or HA only participating in HCA HCAP(Northern Health, Fraser Health and Vancouver Coastal Health)
- HA’s from Vancouver Island and Interior Health should be able to see filter
- MHSU employers from Vancouver Island and Interior Health should be able to see filter

HCAP-1511 - add lived/ living experience filter

---

client/src/components/generic/Notifications.js
client/src/pages/private/ParticipantTable.js
client/src/utils/gen-util.js
client/src/utils/prettifyStatus.js
server/services/employers.ts
server/services/participants-helper/core.ts
server/services/participants/participant-entries.ts

- fix missing site names
- fix irrelevant sites lit
- fix missing status infos

fix participant table

---

client/src/constants/participantTableConstants.js
client/src/pages/private/ParticipantTableFilters.js
client/src/providers/ParticipantsContext.js
server/routes/participant.ts
server/services/participants-helper/RegionsFilteredParticipantsFinder.ts
server/services/participants/participant-entries.ts

- add `Hide withdrawn participants` checkbox filter for MoH users

HCAP-1498 - add hide withdrawn participants filter

---

client/src/components/modal-forms/NewParticipantForm.js
client/src/constants/validation/schema/schema-external-hired-participant.js
client/src/pages/private/ParticipantTable.js
client/src/pages/private/ParticipantTableFilters.js
server/constants/index.ts
server/constants/mhaw-enabled-regions.ts
server/routes/participant.ts
server/services/participants-helper/ProgramFilteredParticipantsFinder.ts
server/validators/external-participant.ts

- remove conditions of only certain HAs having access to MHAW pathway
- allow access to all HAs to MHAW pathway
- add `Are you a Canadian citizen or permanent resident?` question to non portal hire form and do not allow form submit if answer is 'No'

HCAP - allow all HAs access to MHAW pathway

---

client/public/index.html
client/public/snowplow-tracker.js

- add snowplow tracker script to header
[HCAP-1525](https://eydscanada.atlassian.net/browse/HCAP-1525)

HCAP-1525 - add snowplow tracker

---

client/public/index.html

- added meta tag to index.html for google search console verification

HCAP-1524 - add meta tag for google verification

---

server/server.ts

- added src for snowplow script to csp

update csp for snowplow tracker script

---

.github/workflows/build.yml
client/src/components/generic/Footer.js
client/src/components/participant-form/DisabledLanding.js
client/src/components/participant-form/Fields.js
client/src/pages/private/ParticipantFullWithdrawPage.js
client/src/pages/private/ParticipantLandingEmpty.js

BCMOHAM-21655 remove any mentions of the HCAPInfoQuery gov mail address.
Github workflow fix.

BCMOHAM-21655 remove any mentions of the HCAPInfoQuery gov mail address.

---

.github/workflows/build.yml
openshift/patroni.bc.yml
openshift/patroni.dc.yml

Installed OpenShift CLI before starting any steps to avoid having the error message "oc: command not found"

Bcmoham 22972

---

.github/workflows/build.yml
.github/workflows/promote-test.yml

- Put back if conditions in build file
- Update Promote to Test Github Workflow file >> Installed OC

Fix test deployment

---

Makefile

Fix prod deployment 20250311

---

openshift/patroni.bc.yml
openshift/patroni.dc.yml

1. update Patroni StatefulSets:
current resource:
- resources:
limits:
cpu: '2'
memory: 4Gi
requests:
cpu: 500m
memory: 2Gi
update to:
- resources:
limits:
cpu: '2'      
memory: 10Gi   
requests:
cpu: 500m      
memory: 2Gi 
2. lower the num of patroni pods from 3 to 2

update resource requests&limits on patroni statefulsets

---

Dockerfile

- Added ENV npm_config_cache=/dev/null to completely disable the npm cache in all stages
- Added ENV HOME=/tmp to set a writable home directory for npm
- Added --ignore-scripts flag to npm ci commands to avoid running scripts that might cause permission issues
- Added --no-cache flag to the server's npm ci command to ensure consistency

disable npm cache to resolve the permission issue

---

.github/workflows/format.yml
.github/workflows/sonar.yml
.github/workflows/test.yml

Format Check:
Runs on PRs opened, synchronized, or reopened to ANY branch
Sonar Check:
Runs on PRs opened, synchronized, or reopened to ANY branch
Runs on direct pushes to master, dev-env, and test-env branches
Cypress/Jest Tests:
Runs when a tag named "cypress" is pushed
Runs on PRs opened, synchronized, or reopened to master, dev-env, and test-env branches only

Create dev-env and test-env branches for dev&test environment

---

docs/deployment.md

Update deployment documentation on README

Update deployment documentation on README

---

.github/workflows/promote-dev.yml
.github/workflows/service.run.dev.yml
.github/workflows/service.run.prod.yml
.github/workflows/service.run.test.yml
.github/workflows/test.yml

update node.js version from v20 -> v24 on workflow files

update node version on workflow files

---

Dockerfile

Dockerfile update to include .npmrc to client container

Dockerfile update to include .npmrc to client container

---

server/scripts/feed-data.ts

- Fixing connection issues when trying to seed a brand new database.

Fixing seeding script

---

client/src/pages/private/ParticipantTable.js
client/src/pages/private/ParticipantTableDialogues.js
client/src/pages/private/SiteTable.js

JSU-416: Correct the Health Authority dropdown option for employers under 'My Sites' tab
JSU-422: remove 'Add Non-Portal Hire' button for MOH Admin accounts

Jsu 416 employer site fix
