client/src/components/employee-form/index.js, client/src/components/employer-form/index.js, client/src/pages/public/Login.js, server/scripts/parse-xml.js, server/server.js, server/tests/form.test.js
There are a couple of things I didn't update yet, because the FE design isn't even close to final:
- tests
- openAPI spec
Everything should be hooked up FE > BE with validation, although the actual responses are just dummy success messages since the API > DB communication isn't in place yet.
=> Hooked FE up to the API, with endpoint dummy responses

client/src/constants/routes.js, client/src/pages/private/Admin.js, client/src/pages/private/ApplicantUpload.js, client/src/pages/public/Login.js, client/src/routes/index.js
In this PR:
- /login now offers both options, IDIR and BCeID, for login
- FE references have been changed from employee to applicant, including employee-upload to applicant-upload
- Going to /applicant-upload without logging in first will redirect to BCeID login as the default IDP
=> Switched default login to present both options, renamed Applicant on FE

client/src/components/generic/Dialog.js, client/src/components/generic/Table.js, client/src/components/generic/index.js, client/src/constants/validation.js, client/src/pages/private/EOIView.js, client/src/pages/private/ParticipantView.js, client/src/pages/private/UserView.js, server/keycloak.js, server/main.js, server/package-lock.json, server/package.json, server/server.js, server/validation.js
BE route for pending access request approval. Takes user ID (set by Keycloak), region, role (only MoH for now).
Keycloak class takes user ID, array of regions, and a role.
FE has a dialog form that allows choosing a single region and single role for a pending user and approving said user. I'm sure the Dialog component can be improved. Specifically, I think that either the Dialog component or a new component should take some of the responsibility from the UserView component which is getting pretty heavy.
The Table component was updated to improve the way it lays out its cells. Previously, it iterated through the keys of a row item, adding each as a contiguous cell. Now, it iterated through the ID of each header cell and accesses properties of each row item using this key. This allows for …
=> Hcap 187 approve access request

server/server.js
One more directive that’s being flagged by the ZAP Scan.
=> Added form-action directive

client/src/pages/private/ParticipantView.js, server/package.json, server/server.js, server/services/participants-helper.js, server/services/participants.js, server/tests/participant.form.test.js, server/tests/util/extensions.js
Some context: Tried to get a Jest `expect` extension going for comparing raw participant data (seed data in tests) to data returned from the API to employers. Could not get it to work and development is taking far too long as Docker is not updating container FS for me at the moment.
=> Show participants that do not have CRC clear, show callback status

client/src/constants/routes.js, client/src/pages/private/Admin.js, client/src/pages/private/ParticipantTable.js, client/src/pages/private/ParticipantView.js, client/src/pages/private/SiteTable.js, client/src/pages/private/SiteView.js, client/src/routes/index.js, client/src/utils/getDialogTitle.js, client/src/utils/index.js, client/src/utils/prettifyStatus.js, cypress/integration/participantView.spec.js, cypress/integration/siteView.spec.js, cypress/support/commands.js
Prominent Changes:
- Most of the logic in participantsView has been moved to participantsTable, leaving the view as a wrapper for the table
- siteView is a wrapper for the new siteTable, accessible via the admin page
- Some smaller functions have been factored out of participantsTable into utils
Current Issues:
- ~~overall bugginess with how the tables render~~
- ~~sitesView shows all sites by default, regardless of relevance to given health authorities (sometimes?)~~
- ~~"My sites" tab does not exclusively show sites assigned to the health authority~~
=> Views and tables have been decoupled

.config/cypress.env.json.example, .gitignore, server/scripts/participant-stats-hired.js, server/services/reporting.js
Client needed employer emails to cross-reference other data, so did a quick addition.
I also excluded .csv output with gitignore, which reminded me we still had some old cypress config to remove :)
=> Added email to hired report

README.md, client/package-lock.json, server/package-lock.json, server/package.json
Deploying to dev is blocked based on results of npm audit fix, so just applied that to both client/server and also added the README update we forgot for HCAP-392
=> npm audit fix and added last report to README

client/src/components/generic/Header.js, client/src/components/generic/Page.js, client/src/components/modal-forms/NewParticipantForm.js, client/src/components/participant-form/Fields.js, client/src/components/participant-form/index.js, client/src/constants/routes.js, client/src/pages/public/ParticipantConfirmation.js, client/src/pages/public/ParticipantForm.js, client/src/routes/index.js, server/server.js
Participant form is visible at `/participant-form`. It is also shown at `/` depending on hostname. For now, a hostname of `hcapparticipants.gov.bc.ca` will show the participant form at the base path.
=> Hostname-based routing, participant form updates

README.md, client/src/constants/routes.js, client/src/routes/index.js, client/src/utils/misc.js, cypress.json, docker-compose.dev.yml
This PR will only work on dev/test if we create the **hcapparticipants** and **hcapemployers** suffixes. 
To test locally just use **http://hcapemployers.local.freshworks.club/** and **http://hcapparticipants.local.freshworks.club:4000/** instead of localhost:4000
=> Hcap 404 improve routing

server/migrations/1616190016615_post-import-cleanup.js
For all participant records where the postal code is Z1Z1Z1, blank out the postal code entirely
Where the value of a field has been saved in the DB as NULL, replace a blank string or actual null - fields impacted: non-HCAP, CRC Clear. I didn’t find anything else on prod data
=> Added post import migration

Makefile, server/server.js, server/services/employers.js, server/tests/employer.form.test.js, server/tests/employer.site.test.js, server/validation.js
- Discovered nothing was using the existing sites POST endpoint - all our scripts to create sites go directly via the DB using saveSites in employers.js
- Repurposed the existing endpoint to be a single site POST endpoint, limited to MOH and with new validation
- The main validation difference between POST/PATCH is that single site POST requires Site ID, and also supports Operator Name - these are both already supported in the batch DB operation (which has its own validation as well)
Incidentally this is how I'm noticing we forgot to put the Operator Name in the single site view FE. 🙃 
Other cleanup:
- Split the employer form (EEOI) tests vs. site tests into separate files
- Added new tests for single site POST
=> HCAP-389: Single site POST - BE

cypress/integration/participantView.spec.js
I spent some time trying to figure out what was causing it to fail now and not before, but eventually decided that clicking on the button wasn't necessary for testing either way. Simple fix.
=> don't click on the disabled button

client/src/constants/routes.js, client/src/routes/index.js, client/src/utils/misc.js
Simplified the logic behind how URL matching is performed. 
Resolving the 'invalid parameter: redirect_uri' involved altering one of the client values in keycloak to a wildcard match, which may need to be specified further in the case of non-local deployments.
We could also use a more intricate regex to match all of the hostnames for dev, test, and prod as well but brain hurt.
=> www. is now a valid subdomain for redirection

client/src/pages/public/ConfirmInterest.js, server/services/participants.js
https://freshworks.atlassian.net/browse/HCAP-606
Add criteria so we only update records that match the initial query.
- Don't update PEOI where `interest` = `withdrawn`
- Don't update PEOI where `userUpdatedAt` > 6 weeks ago
Also fixed bug on the FE component where I implemented fetch like Axios by accident
=> HCAP-606 confirm interest criteria

server/scripts/sendEmailBlast.js
Sends a test request to the health endpoint and if it fails it updates the token, this will save us from having to batch the emails (if we decide we don't want to)
Sample output: 
```
Blasting 9 emails...
Sent 0 to 1: 60.18s, 0.0/s
Sent 1 to 2: 60.19s, 0.0/s
Sent 2 to 3: 60.20s, 0.0/s
Sent 3 to 4: 60.19s, 0.0/s
Sent 4 to 5: 60.20s, 0.0/s
Token Expired, Reauthorizing...
Success, Token Reauthorized!
Sent 5 to 6: 60.22s, 0.0/s
Sent 6 to 7: 60.14s, 0.0/s
Sent 7 to 8: 60.13s, 0.0/s
Sent 8 to 9: 60.12s, 0.0/s
Sent 9 emails in 541.57s at a rate of 0.02
There were 0 failed sends.
[]
Process complete
```
=> CHES auto reauthorization

server/migrations/1622565479621_update-otp-table.js, server/scripts/sendEmailBlast.js
Serial email sending, better UX, logging to mongo on hard failures
Script takes rate, retry limit, and retry delay as input
If an email fails `retryLimit` times, it's logged to mongo and skipped
=> Email blast v2

server/server.js, server/services/participants.js
* fixed issue where the confirm-interest submit route was checking only records that had not been updated in the past 6 weeks. 
* Fixed issue where the change to the interested column is changed without logging the change. 
* Will now fail if no otp is deleted or no rows were updated. 
https://freshworks.atlassian.net/browse/HCAP-610
=> Confirm interest Logic update

client/src/constants/validation.js, client/src/pages/private/ParticipantTable.js
It turns out that for some reason, up doesn't display validation errors on fields that are undefined. 
Before the active participant is assigned, if the postalCode is undefined, I set it to the empty string so Yup has a value to check.
=> Fixed filter

client/package-lock.json, client/package.json, client/src/components/generic/Table.js
The pagination component was rendering (total_participants / 10) elements every time the page loaded. I added react-window to virtualize this list to keep the same functionality while reducing the lag to practically 0
https://freshworks.atlassian.net/browse/HCAP-663
Reference: https://material-ui.com/components/lists/#virtualized-list
=> HCAP-663 Pagination Performance

cypress/fixtures/participantTableTabs.json, cypress/integration/participantTable.spec.js, cypress/integration/participantView.spec.js, package.json
https://freshworks.atlassian.net/browse/HCAP-694
Disabled linting in tests because there were some strange incorrect errors being thrown
These tests are meant to define which columns/tabs should render based on role/selected tab for `participantTable`
=> HCAP-694 participant table tests

client/src/constants/participantTableConstants.js, client/src/pages/private/ParticipantTable.js, client/src/providers/ParticipantsContext.js
Also simplified how participant context calculates state based on auth (it consumes the auth context and doesn't need to be updated from participantTable)
=> Lift Tab State (HCAP-660 #4)

client/src/constants/participantTableConstants.js, client/src/pages/private/ParticipantTable.js, client/src/pages/private/ParticipantView.js, client/src/providers/ParticipantsContext.js
This branch removes the complex logic and decisions that build the array of columns used in the table depending on the role and selected tab.
A previous PR introduced new data objects + context that we can use to lift up state and simplify logic across this component. 
https://freshworks.atlassian.net/browse/HCAP-660
- Rerenders on this component have been reduced from >20 to ~5 (still some work to do)
- UseEffect activations are down from ~6 to 2
- Unnecessary network calls have been prevented (participants are only fetched once)
- Lift Tab state into context
- Add asynchronous actions to context for API requests
- Split components
- Lift rest of state (where it makes sense)
=> Use state to determine columns (HCAP-660 #3)

client/src/constants/validation.js, server/validation.js
Updated validator to fix issues with endDate. 
The format of the string returned in certain circumstances did not match the expected pattern. 
Made endDate only validate when the type is "employmentEnded"
=> V2.19 hotfixes

client/src/constants/participantTableConstants.js, client/src/pages/private/ParticipantTable.js, client/src/pages/private/SiteParticipantsTable.js, server/services/participants-helper.js, server/services/participants.js
Fixed HCAP-715 - Issue where the incorrect key and shape were used to check if a user was MoH in the SiteParticipants table. 
Improved the function of  HCAP-695 
- When navigating between tabs on the participant table, if you are on a page with a page number that is greater than the page total for the tab you are navigating to, you will be shown the first  page of that tab. The number will still be wrong as I haven't figured out why the component isn't updating. This also causes the page switch feature to respond improperly ( The component is set to the wrong page, so it wont update correctly until the user uses the controls to update it to the correct page. 
Fixed HCAP-696 
When a MoH withdraws a hired participant, their participant statuses were not being updated. 
Now when a MoH worker …
=> Hcap 696 final showdown

server/Dockerfile.dev
Swapping out the docker image version based off of wills suggestion. Hopefully this should bypass dockerhubs pull limit.
=> Switched to bitnami node docker image

client/.dockerignore, server/.dockerignore
Before: 
```
Building server
Sending build context to Docker daemon  125.9MB
Building client
Sending build context to Docker daemon  261.1MB
```
After 
```
Building server
Sending build context to Docker daemon  9.435MB
Building client
Sending build context to Docker daemon  3.901MB
```
=> Stop sending node modules in build context

server/routes/index.js, server/routes/user.js, server/tests/user-details.e2e.test.js
N.B: Keeping route `/users`, `/approve-user` and `/user` in API root route. This three routes are completely has no common prefixes, so creation of three different router would be pure overhead.
=> HCAP-706 | HCAP-793: Separate user-details route.

client/src/pages/private/CohortTable.js, client/src/pages/private/PSIViewDetails.js, cypress/integration/psiDetailView.spec.js
Dates now display accurately, past cohorts are identified as closed. Cypress tests added.
Addresses https://freshworks.atlassian.net/secure/RapidBoard.jspa?rapidView=206&modal=detail&selectedIssue=HCAP-818
and https://freshworks.atlassian.net/secure/RapidBoard.jspa?rapidView=206&modal=detail&selectedIssue=HCAP-817
=> HCAP-817 | HCAP-818 | Date Display and Past Cohorts

client/src/constants/label.js, client/src/pages/private/PSITable.js
Deconstructed the regionLabelsMap to remove 'None'.
https://freshworks.atlassian.net/browse/HCAP-808?atlOrigin=eyJpIjoiMzA4NjgyOTVmZDJmNGJkYzk0OWQ0NmI3MzI0NGYwYjciLCJwIjoiaiJ9
=> HCAP-808 | customised regions table to avoid 'None'

client/src/pages/private/ParticipantTable.js
This dispatch was breaking the component state, it seems like a mistake (passing pagination to the select tab action?) and the app seems to work great without it.
[MOH/HA/Employer > Blank screen on various actions](https://freshworks.atlassian.net/browse/HCAP-827)
=> HCAP-827 | remove unneeded state call

client/src/pages/public/ParticipantForm.js, server/routes/participant.js
Replace the form with Temporary Closure copy. 
Also close down the submission route. Since tests are broken locally, I apologize if this breaks tests when the PR is published.
Mobile View
Regular view
=> Hcap 851 close participant form

server/migrations/1629228977039_remove-duplicates.js
Migration to remove duplicate archived or rejected statuses. 
This is causing the pagination to display incorrect results on the Archived Candidates tab. (HCAP - 850)
=> HCAP-850 Migration

server/services/participants.js
Since id is a unique key, we do need any other keys to make the update here. 
Having an incorrect value for participant id here was causing the previous not to be updated.
=> Hcap 906 redux

client/src/pages/public/ParticipantLogin.js
Looks like MUI buttons automatically capitalize each word. This conflicted with BC gov style guide-lines.
=> Fixed W capitalization on login button

.config/.env.example, .docker/keycloak/realm-testing.json, .docker/keycloak/users.json, .eslintignore, .eslintrc, .github/workflows/test.yml, Makefile, client/src/pages/private/ParticipantLanding.js, cypress.json, cypress/.eslintrc, cypress/fixtures/participant-data.json, cypress/fixtures/users/test-participant.json, cypress/integration/participant-landing.spec.js, cypress/integration/psiDetailView.spec.js, cypress/integration/psiView.spec.js, cypress/integration/siteViewDetails.spec.js, cypress/integration/userView.spec.js, cypress/support/commands.js, docker-compose.dev.yml, docker-compose.test.yml, package.json, server/routes/participant-user.js, server/routes/participant.js, server/server.js, server/services/participants.js, server/validation.js
1. Update Local KeyCloak config to support participant user
2. Add cypress tests
3. Add optional end point to delete all participant with given email
4. Add few make alias 
5. Add some npm script to run cypress
6. Add data fixture for tests
Ticket: [HCAP-737](https://freshworks.atlassian.net/browse/HCAP-737)
=> HCAP-737 | Cypress E2E Tests for Participant pages

server/tests/util/keycloak.js
Looks like hard coding the password for the participant test user was being flagged by scans. This isn't really an issue, but I added an environment variable to match the rest of the test users.
=> Added env for participant password

client/public/index.html, server/server.js
- Middleware to generate a nonce per-request
- Inject nonce to `index.html`
- Once for the script files
- Once for the meta tag to be consumed by JSS
- Use the same nonce in the CSP
https://freshworks.atlassian.net/browse/HCAP-978
=> HCAP-978 | Fix CSP by applying a nonce to inline scripts and styles

client/src/components/modal-forms/IndigenousDeclarationForm.js, client/src/components/participant-form/Fields.js, client/src/components/participant-form/index.js, client/src/constants/theme.js, client/src/constants/validation.js, client/src/pages/private/ParticipantLanding.js, client/src/utils/isNonPortalHire.js, server/routes/participant-user.js, server/validation.js
- Participants who log in and have a PEOI without an indigenous identity answered see the form
- Form submission updates all associated PEOIs (1 network request per PEOI, should I create a bulk edit endpoint?)
- After speaking with David, this will be upgraded to a batch edit feature (apply edits across all of a user's PEOIs)
- Includes fixes for HCAP-981 
- Read only version of these new questions viewable on PEOI form
- Add styling for `h4` + `h5`
- Validation: First question optional, if first question is 'Yes', second question is required
- New `participant` fields:
```
isIndigenous?: boolean;
identities: indigenousIdentityOptions 
const indigenousIdentityOptions = {
FIRST_NATIONS: 'first-nations',
INUIT: 'inuit',
METIS: 'metis',
OTHER: 'other',
UNKNOWN: 'unknown',
}
```
=> HCAP-931 + HCAP-981 | indigenous question

client/src/components/participant-form/Fields.js
The questions aren't rendered when a participant selects "No", it should only not show if the answer is null or undefined.
=> HCAP-931 | Check for nullish, not falsey

client/src/pages/private/ParticipantTable.js
Looks like lodash's math library ceased to exist. It was causing a white screen of death whenever a site distance calculation was called. I replaced it with the regular math library and it seems to work fine.
=> HCAP-990 Fixed site distancing bug

client/src/pages/private/ParticipantLanding.js
When `interested === null` the following status is shown
https://freshworks.atlassian.net/browse/HCAP-941
=> HCAP-941 | Add content for interest = blank

.gitignore, client/src/components/modal-forms/ArchiveHiredParticipantForm.js, client/src/constants/archiveParticipantsConstants.js, docker-compose.dev.yml, docker-compose.test.yml, server/validation.js
- Add new archive reason 'Failed cohort, does not wish to continue in HCAP'
- Only Keep single status 'Post secondary education underway' after above mentioned reason selection 
- In local dev, update docker compose to attach volume from local file dir.
Ticket: [HCAP-1032](https://freshworks.atlassian.net/browse/HCAP-1032)
=> HCAP-1032 | Add new archive reason - 'Fail Cohort'

.github/workflows/build.yml
Current build workflow checking out `dev` ref (tag) to get commit sh as build id. Which is conflicting with PR merge workflow (pushing commit in master branch).
New workflow checkout code based on event source (branch: master / tag:dev)
=> Fix Git Build Issue | Fix PR merge deployment

client/src/components/modal-forms/EditParticipantForm.js, client/src/pages/private/ParticipantDetailsView.js, cypress.json, cypress/integration/editParticipant.spec.js, cypress/integration/participantView.spec.js, cypress/support/commands.js
I've fixed cypress tests for me locally (for the most part) .
Some environment variables needed. 
-- AUTH_URL needs to be set to the local keycloak url, http://keycloak.local.freshworks.club:8080/auth
-- The port of the backend url needs to be set to 8081
-- KEYCLOAK_LOCAL_AUTH_URL needs to be set to the same as the auth URL 
Keycloak needs some configuration 
-- The local service account needs to have it's password reset 
-- The local keycloak client secret needs to be set 
I rebuilt the login flow for local by copying the headers/paramteters that my browser used into postman and then translating that into cypress. 
Because the two login processes were quite different, I split them into two separate functions. I tried adding a variable into cypress.json to track this, but for some reason …
=> Hcap 789 fix local cypress tests

client/src/components/participant-details/track-graduation.js, client/src/services/participant.js
=> HCAP-1033 | HCAP-1087 | HCAP-1088 | BugFix | Update unsuccessful cohort label with date

server/routes/participant.js, server/services/participants.js, server/tests/employer-action.e2e.test.js, server/tests/participant-status.test.js, server/tests/participant.test.js, server/validators/participant.js
=> HCAP-1107/1168 | Update service and api route to handle sites for prospecting statuses

Makefile, server/constants/index.js, server/constants/participant-status.js, server/services/participants-helper.js, server/services/participants.js, server/tests/participant-status.test.js
Ticket: [HCAP-1140](https://freshworks.atlassian.net/browse/HCAP-1140)
=> HCAP-1140 | Enable MultiOrg display of prospecting statuses

client/src/constants/participantTableConstants.js
Marking last engaged by column unsortable so that the sorting UI does not cause it to crash.
=> HCAP-1106 | unsortable last engaged by column

client/src/constants/participantTableConstants.js, server/constants/validation-constants.js, server/services/participants-helper.js
https://freshworks.atlassian.net/browse/HCAP-1106
- This is the second part of this story, the column has been added previously, now it is sortable.
- On first click, it sorts reverse alphabetical (2 clicks for alphabetical). However, I noticed that the Last Name column does as well.
=> HCAP-1106 | Make Last Engaged By column sortable

client/src/components/modal-forms/SelectProspectingSiteForm.js, client/src/pages/private/ParticipantTable.js, client/src/utils/prettifyStatus.js
https://freshworks.atlassian.net/browse/HCAP-701
This PR fixes the issue with statuses being displayed as `Open` for MoH. Still, I feel like there're a few more tests needed
I'd appreciate any input at this point 🙌 
I'm adding some refactoring as well 🖌️ 
**My questions:** ❔ 
1. I noticed there's a field we're generating on BE called `statusInfo`. Is it used somewhere?
2. When HA archives a participant, they have an option to select: _Withdrawn at participant request_. If they select this option - should the status change to `rejected` or `withdrawn`?
3. What should be the status for archived participants assuming they're not available to any employers?
=> HCAP-701: fix MoH participant 'Open' status

client/package-lock.json, client/package.json, client/src/components/modal-forms/ArchiveHiredParticipantForm.js, client/src/components/modal-forms/ManageGraduationForm.js, client/src/components/participant-details/track-graduation.js, client/src/index.js, client/src/pages/private/ParticipantLanding.js, client/src/pages/private/ParticipantTable.js, client/src/pages/private/SiteParticipantsTable.js, client/src/services/return-of-service.js, client/src/utils/date.js, package-lock.json, server/package-lock.json, server/scripts/stats.js
https://freshworks.atlassian.net/browse/HCAP-1125
- replaced moment with dayjs in client packages
- dayjs/moment (or other date libraries) are a dependency of the MUI Pickers Utils Provider, used their [installation instructions](https://material-ui-pickers.dev/getting-started/installation)
- the instructions said to use an older version than what is used for the server, which is also older than what's available to install, want to verify that we *must* use the older version
- TODO: seek and destroy instances of manual date parsing
=> HCAP-1125 | Use uniform date library on client & server

client/package-lock.json, client/package.json, package-lock.json, package.json, server/package-lock.json
https://freshworks.atlassian.net/browse/HCAP-1132
This PR fixes all `npm audit` and Dependabot alerts for `hcap/client` 🎉 
https://github.com/bcgov/hcap/security/dependabot?q=is%3Aopen+manifest%3Aclient%2Fpackage-lock.json+sort%3Aseverity
=> HCAP-1132: fixing dependabot alerts in `client/package-lock`

client/src/constants/theme.js, client/src/pages/private/ParticipantTable.js
- date added
- format according to MMM DD, YYYY
- made classes for the cell text in participant table
- added that darker grey colour to theme palette
- did not change the sorting (sorting by date not desired, already sorting by name)
Could have instead used Typography instead of classes? Not sure if we like div but it gets the job done.
Updated:
- investigated using Typography instead: v4 of MUI does not support custom variants, the feature was added in v5. None of our existing variants matched the design (all bold variants were much larger or the button variant has a text-transform). Did not want to modify variants used elsewhere.
- changed div to Box
- renamed that class to Alva's suggestion
- did not follow the design _exactly_ as it had the staff name text larger than the date. The …
=> HCAP-1106 | Add date to last engaged by column

client/src/components/modal-forms/SelectProspectingSiteForm.js, client/src/constants/validation/schema/schema-select-prospecting-sites.js, client/src/pages/private/ParticipantTableDialogues.js, client/src/services/feature-flag.js
https://freshworks.atlassian.net/browse/HCAP-1190
Changing `SelectProspectingSite` form to allow pick only 1 site during prospecting for both `Engage` and `Bulk Engage`
=> HCAP-1190: updating SelectProspectingSite to single select

server/utils.js
- Error is being caused by attempting to do string operation on a number
- Solution: turn the number into a string so that we don't need a separate function for strings and numbers
=> HCAP-1035 | No duplicate site ID error while creating a new site with duplicate site ID

client/src/components/generic/Table.js, client/src/pages/private/ParticipantTable.js
https://freshworks.atlassian.net/browse/HCAP-1209
Very small fix for multi-select
**What's included:**
- removed `setSelectedParticipants([]);` from `handleEngage()`
🗒️ _Note_: this action is already captured in `handleClose()` 
- updating condition for _Bulk Engage_ button; it's enabled only if >= 1 rows selected
=> HCAP-1209: fixing bulk-engage bug

client/src/components/generic/Notifications.js, client/src/components/generic/Page.js, client/src/components/generic/ParticipantStatus.js, client/src/components/participant-details/track-graduation.js, client/src/constants/theme.js, client/src/pages/private/ParticipantTable.js, client/src/pages/private/ParticipantTableDialogues.js, client/src/pages/private/SiteParticipantsTable.js, client/src/providers/AuthContext.js, client/src/services/index.js, client/src/services/notifications.js, client/src/utils/prettifyStatus.js, server/routes/index.js, server/services/user.js
Ticket: https://freshworks.atlassian.net/browse/HCAP-1189
For sure some room for improvement in prettifyStatus, particularly interested in feedback on:
- change the name of the file? Took all the front-end stuff out of here, name no longer reflects purpose
- similarly, put ParticipantStatus in components/generic. _Is it_ generic? Didn't see any better fits, does it justify its own new directory?
- I sacrificed brevity for clarity and made lots of variables. Looking for opportunities to simplify this where possible while maintaining readability.
- I have a boolean `isHiredByPeer = status[1] === 'hired_by_peer'`, in another place the logic was looking for `status.includes('hired_by_peer')`- will these **always** be the same? If so I'd like to simplify it. Probably other …
=> HCAP | End of ROS Notification

client/src/components/modal-forms/ManageGraduationForm.js, client/src/constants/validation/schema/schema-participant-post-hire-status.js
The field is pre-populated with `cohort-end-date`. So, no need for UI validation.
=> HCAP-1246 | BugFix | Remove date validation for graduation date

client/src/constants/participantTableConstants.js, client/src/pages/private/ParticipantTable.js, cypress/fixtures/participantTableTabs.json, server/constants/validation-constants.js, server/services/participants-helper.js
https://freshworks.atlassian.net/browse/HCAP-1252
Added a new column `Last Engaged Date` to allow sorting by date + renamed `engagedBy` to --> `lastEngagedBy` for clarity
=> HCAP-1252: splitting Last Engaged By column for sorting

README.md
- Add headings for the different how-to sections
- Add separate instructions for running cypress/e2e (importantly adding the step to import local KC users)
=> README-How-to: Add headings, split unit and e2e testing instructions

client/src/pages/private/ParticipantEOI.js
Rename enableEdit to a clearer name
Disable button if logged in participant is withdrawn
=> fix: disable edit button for withdrawn participants

.github/workflows/reminders.yml
I like this feature of this action, it helps to parse the list of PR reminders for which ones require your attention
=> Add github-provider-map for GH -> Slack link

server/services/participants-helper.js
https://freshworks.atlassian.net/browse/HCAP-1304
Basically, my candidates was showing a user who has already gotten ROS for a site I don't have access to and making them actionable. In talking with Tavy, we've determined that if a user gets hired for a site I don't have access to, there can be no further action on that participant.
In this PR, we're doing an inner join which means the participant no longer gets returned if they were ROS'd for a site I don't have access to. This should be okay for now. (Ideally, the participant will be returned with an empty `rosStatuses` so that they show up and still need to be acknowledged, but I was having some trouble).
=> fix: ignore ROS if participant is not in my sites

client/src/pages/private/ParticipantTableDialogues.js
This causes an infinite loop if you run the app without sites in the database
=> fix: infinite loop when database has no sites

client/src/constants/participantTableConstants.js, client/src/pages/private/ParticipantTable.js, cypress/fixtures/participantTableTabs.json, server/db/schema.js, server/migrations/1660318202044_update_participant_status_infos.js, server/services/participants-helper.js
Ticket: https://freshworks.atlassian.net/browse/HCAP-1234
- server/services/participants-helper.js
- rosStatuses didn't return _at all_ for MoH/SU, necessitating some logic changes
- server/migrations/1660318202044_update_participant_status_infos.js
- updated the view used in participants-helper used for MoH/SU. This is the only usage of this view, so I changed the view to return what was missing (rosStatuses namely)
- client/src/constants/participantTableConstants.js
- added rosStartDate to list of columns. I'm actually not 100% sure on the tabs/tabStatuses though
- client/src/pages/private/ParticipantTable.js
- got some undefined errors after bringing in rosStatuses for MoH here, basically added null checks in a few places.
=> HCAP-1234 | RoS Start Date Column For MoH (+SU)

client/src/components/modal-forms/ManageGraduationForm.js
Ticket: https://freshworks.atlassian.net/browse/HCAP-1309
- After changing the purpose of the date field, I made it so that it was "untouched" to not trigger the error message. 
- Bonus: now when going Unsuccessful-> attempt submit-> Graduated-> Unsuccessful, the error message from the first unsuccessful submit does not appear again when status changed to unsuccessful again
=> HCAP-1309 | Graduation date error message

.github/workflows/test.yml
I noticed the build step was taking a really long time (~5mins) so it seems like something has broken down with the docker caching steps. I'll remove them for now and hopefully take another look some day
- Disable docker layer caching
=> HCAP-1320 test failures

openshift/backup-mongo.dc.yml, openshift/backup.dc.yml, openshift/server.dc.yml
Update template to match what's seen in openshift docs: https://docs.openshift.com/container-platform/4.7/openshift_images/using-templates.html#templates-writing_using-templates
Successful run: https://github.com/bcgov/hcap/actions/runs/2916207111
Weirdly [patroni's deployment config](https://github.com/bcgov/hcap/blob/dev/openshift/patroni.dc.yml#L2) was the only one with this apiVersion
=> fix: broken deploy pipeline, update k8s apiVersion

server/services/participants-helper.js
Ticket: https://freshworks.atlassian.net/browse/HCAP-1323
Source of bug was that it was trying to sort on the column rosStatuses, but for Moh/SU, the query is different, it uses a view that had to have a different column name because it can only be lowercase name. First I changed it to just look at the right column in the code block that deals specifically with the sorting, but then I decided to move it up into the context/variable definition as that should also avoid future bugs and be less complex.
=> HCAP-1323 | RoS Start Date Column Sorting

server/routes/milestone-report.js, server/services/reporting.js
https://freshworks.atlassian.net/browse/HCAP-1319
**Cause of this bug:**
`additionalEntries` are responsible for including participants outside of HAs region in the reports; this can happen due to RoS site change, for example
The issue was that it only included entries with `status = 'assigned-new-site'` - this status is valid when assigning a new site as HA; yet when MoH makes an edit, this status is not being assigned
**Proposed fix:**
Include all edited entries in the report, if they apply to the same health region as HA at any point.
This can be done y identifying updated entries: `'data.user <>': 'NULL'` and checking if HA is allowed to see them based on region
**What else included?**
Splitting `getRosReport` into `getMohRosMilestonesReport` and `getHARosMilestonesReport`
=> HCAP-1319: HAs can see participants in the reports after MoH makes changes

client/src/components/participant-details/track-graduation.js, server/routes/participant.js, server/services/participant-details.js, server/services/participant-status.js
https://freshworks.atlassian.net/browse/HCAP-1308
Some consistency for Archiving.
In short, archiving from the table view in Hired Candidates passes in `site` and `currentStatusId`, both of which aren't passed in from the Participant Details view archiving. Akhil confirmed to me that for non-MoH users, Participant Details screen is only available for hired participants, so we can assume that they were hired here.
As such, we make the backend participant details endpoint return all current statuses, which in this case should really just be hired or archive. We then use those values to make it consistent with the table archive. We expect that there should only be one `hired` status, if at all. If there isn't a `hired` status, this endpoint should fail.
Why? There is a query in in the …
=> fix: using current hired status when archiving

server/services/participants-helper.js
https://freshworks.atlassian.net/browse/HCAP-1324
The date wasn't sorted for MoH because it couldn't find `ros_infos.data.date` for MoH. Therefore, it sorted by `id` by default. The reason why it couldn't find `ros_infos.data.date` field was because it's an array - it can only get the actual date by getting a specific item `ros_infos[0]`
=> HCAP-1324: RoS start date sorting fix for MoH

client/src/services/return-of-service.js, server/routes/employer-sites.js, server/routes/index.js, server/services/employers.js, server/tests/employer.form.test.js, server/tests/employer.site.e2e.test.js, server/tests/employer.site.test.js
Notes: 
- Many places in the app refer to `user.sites` to list sites
- `GET /user` retrieved all sites then filtered by site ID, this wasn't sorted
Attn:
- In order to properly define test cases in isolation I needed to close and open the db between test cases which adds >10s to this test suite. This is because of some strange behaviour from Massive when attempting to clear the employer_sites table.
- When switching to use `saveSites` I noticed a difference in the validation schemas for the various site editing/creation endpoints which led me to create `batchSiteObject`. I think this isn't great and I'd love feedback on fixing this. Should we make large scale changes to validation/controllers/client to address these inconsistencies?
Changes:
- I consolidated the two getSites methods and …
=> HCAP-1314 Consolidate getSites methods

server/services/employers.js
Forgot to account for changes in HCAP-1333 which limited the data returned from `getSitesForUser`
=> HCAP-1315 expose site city to FE

client/src/constants/routes.js, client/src/pages/private/CohortDetails.js, client/src/pages/private/CohortTable.js, client/src/pages/private/PSIView.js, client/src/pages/private/PSIViewDetails.js, client/src/routes/index.js, client/src/services/participant.js, client/src/services/psi-cohort.js, server/routes/cohorts.js, server/services/cohorts.js
https://freshworks.atlassian.net/browse/HCAP-1039
Creating a new `CohortDetails` page to show
- Start date
- End date
- Capacity
- Availability
- Number of unsuccessful participants
There's a separate ticket to display a list of participants attached to this cohort --> https://freshworks.atlassian.net/browse/HCAP-1056
https://www.figma.com/proto/35c5C0DyTEOxJ4N4DIaADL/HCAP-Design?node-id=2441%3A37315&viewport=241%2C48%2C0.37&scaling=min-zoom&starting-point-node-id=2441%3A37147
=> HCAP-1039: view cohort details page

client/src/services/psi-cohort.js
https://freshworks.atlassian.net/browse/HCAP-1343
TBH, I'm not sure why this started failing, but it did. No where else seems to really use that baseURL pattern so this is more consistent anyway.
=> fix: remove base url

Makefile, README.md
https://freshworks.atlassian.net/browse/HCAP-1317
- Adds documentation on how to set feature flags
- Remove feature flags from makefile, treat `.env` as the source of truth for local development
=> HCAP-1317 Feature flag docs

client/src/components/modal-forms/EditRosSiteForm.js, client/src/components/modal-forms/SelectProspectingSiteForm.js, client/src/pages/private/UserView.js
https://freshworks.atlassian.net/browse/HCAP-1341
I guess lodash and postgres treat spaces differently in their sorting algorithms
- removed extra sort on FE for sitenames
=> HCAP-1341 Remove additional unneeded sorting

client/src/pages/private/CohortTable.js, server/services/cohorts.js
- Calculating this field on the server allows us to treat it like any other field on the FE which fixes our sorting problem
https://freshworks.atlassian.net/browse/HCAP-1355
=> HCAP-1355 Calculate remaining seats on the server

client/src/pages/private/CohortDetails.js, client/src/pages/private/ParticipantDetailsView.js, server/routes/cohorts.js, server/services/cohorts.js, server/services/participant-details.js, server/tests/cohort.service.test.js, server/tests/participant-details.e2e.test.js
https://freshworks.atlassian.net/browse/HCAP-1358
- Open HA participant access to all participants within their region
- Limit cohort participant query to only participants within HA's region
- Fix available seats count on details page
- Calculate remaining seats on server
- Solution is to combine the participants and details queries so we don't make duplicate service requests
=> HCAP-1358 HA participant access

client/src/pages/private/CohortDetails.js
This alert should only be visible to HAs because MoH can see all participants
=> HCAP: remove alert for MoH

server/routes/cohorts.js, server/services/cohorts.js
https://freshworks.atlassian.net/browse/HCAP-1361
Notes:
- Previous join was joining any participants statuses which made it indeterminate which status would be retrieved
- This would often join statuses that don't contain `data.site` which means the siteJoin would be null
- Null site join caused issues with the new HA region access code
Solution:
- Additional logs on get cohort failure
- Only join hired statuses so we are more confident it will populate the siteJoin
- We have seen hired statuses without 'site' but these are very invalid and we should delete them as we see them, they will cause the same crash when stumbled upon though
=> HCAP-1361 Get Cohort ISE

server/services/cohorts.js
Only counting current participants should stop us counting duplicate assignees to a single cohort
https://freshworks.atlassian.net/browse/HCAP-1364
=> HCAP-1364 Cohort participant count

server/services/cohorts.js
- Oversight from the last fix was that joining on `hired` would omit `archived` participants, we run into issues when we combine archived and hired participants in the same join so I split them up into two joins
- When combining hired and archived into `participantStatusJoin` we can't guarantee `siteId` will be populated because some archive statuses don't have `siteId`
- By splitting them up, we ensure we get all hired and archived participants, and can also be much more confident `siteJoin` will populate by referring to the hired status
https://freshworks.atlassian.net/browse/HCAP-1363
=> HCAP-1363 Separate joins for hired and archived status

.github/workflows/build.yml, .github/workflows/promote-prod.yml, .github/workflows/promote-test.yml, .github/workflows/reminders.yml
Ticket: https://freshworks.atlassian.net/browse/HCAP-1332
- Uptime Robot alert 
- 
- tested and verified
- I did also subscribe the HCAP alerts channel to the FW keycloak monitor (which it was not before)
-  PR Reminders:
- 
- kept same action (https://github.com/DavideViolante/pr-reviews-reminder-action)
- updated to use Teams
- not any examples of the user IDs for teams, so I assumed email
- have not actually confirmed that this will work as desired
- uses GH secret MS_TEAMS_WEBHOOK_URI to connect to a channel- modify secret to change channel
-  Deploy Alert:
- 
- using action https://github.com/toko-bifrost/ms-teams-deploy-card (see for config documentation)
- also uses GH secret MS_TEAMS_WEBHOOK_URI
- I have it set to send a notification on exit, and not show on start (ie: will not …
=> HCAP-1332 | Deployment alerts for MS Teams

server/services/cohorts.js
https://freshworks.atlassian.net/browse/HCAP-1364
I forgot about reassigning, this is similar to a part of a fix @alva-fresh made before, but calculated on the server to reduce FE changes
=> HCAP-1364 Dedupe cohort participants

client/src/pages/private/SiteTable.js, server/services/employers.js
This subquery is causing performance issues on prod, we'll need to disable it for now and work on a more performant solution in the future
=> fix: remove hirecount to fix performance issues

server/migrations/1661284647061_add-phase-tables.js, server/migrations/1661465391816_allocation_migration.js
[HCAP-1296](https://eydscanada.atlassian.net/browse/HCAP-1296)
This PR moves the migrations for Phase Allocation tables to the right folder, so that it will actually apply on dev. In [this ticket](https://eydscanada.atlassian.net/browse/HCAP-1276) we identified that this is the way to do it. To see what the tables look like in general, please see [this ticket](https://eydscanada.atlassian.net/browse/HCAP-1296) and [PR#818](https://github.com/bcgov/hcap/pull/818/files).
=> fix: apply phase allocation database changes

README.md, docs/development.md
[HCAP-1378](https://eydscanada.atlassian.net/browse/HCAP-1378)
This PR adds some detail to the readme and development documentation regarding prerequisites, setup, and running on Windows. It also moves the Features section down for faster access to Development, and fixes the misleading use of localhost in the setup instructions.
=> HCAP-1378 - Add additional prerequisites to readme

server/keycloak.js, server/routes/phase-allocation.js, server/services/employers.js
[HCAP-1336](https://eydscanada.atlassian.net/browse/HCAP-1336)
This PR prevents non-MoH users from accessing sites they do not have access to. It also adds a bit of documentation and typing to functions related to the `phase-allocation` endpoint.
It should be noted that this does NOT fix [HCAP-1391](https://eydscanada.atlassian.net/browse/HCAP-1391) (allowing MoH users to get invalid site allocations). That issue should be handled separately.
=> HCAP-1336: Authenticate user's sites when fetching site phase allocations

client/src/pages/private/PhaseView.js, client/src/pages/private/SiteViewDetails.js
HCAP-1392
A quick renaming of the breadcrumbs to match design
=> fix: rename breadcrumbs to view sites

server/db/db.js, server/routes/employer-sites.js, server/routes/phase-allocation.js, server/services/employers.js, server/services/phase.js, server/tests/employer.form.test.js, server/tests/employer.site.test.js
[HCAP-1334](https://eydscanada.atlassian.net/browse/HCAP-1334) (blocks [HCAP-1298](https://eydscanada.atlassian.net/browse/HCAP-1298))
Also fixes [HCAP-1391](https://eydscanada.atlassian.net/browse/HCAP-1391)
This PR optimizes the code used to get the phase allocation and hires for a given site. DB impact is now limited to two queries, and only the data needed is sent over the wire.
In addition, this PR:
* Expands the capacity for custom queries in the DB wrapper
* Simplifies the return type of `getSiteByID` (was an array with only one element, now directly returns the element) and updates all dependent code
* Adds typing in a few related places
=> HCAP-1334: Optimize query for joining hires to site phase allocations

server/services/phase.js
The `getAllSitePhases` was referencing the incorrect FK id between allocations and sites, updated to use the `id` column, not the form input column `siteId`
id = 8
Updated UI
site_phase_allocation in the db matching site_id = 8
=> Update to FK reference on site_phase_allocation to employer_site

client/src/pages/private/SiteTable.js, server/routes/phase-allocation.js
- Fixes 403 Forbidden error when fetching Global Phases on Allocation tab
- HA users have access to view Global Phases
- MOH users have access to view Global Phases
- Employers do not have access to view Global Phases
- Removed the 'details' button on the Employer Sites table as employers do not have access to view the details page. 
- Previous view for employers after clicking 'details'
- 'Details' button removed
=> Updated global phases GET permissions

README.md, docs/development.md
[HCAP-1412](https://eydscanada.atlassian.net/browse/HCAP-1412)
jq wasn't listed upfront in the list of dependencies. This PR adds it to prevent surprises when running scripts.
=> HCAP-1412 - Added jq to list of prerequisites

server/package.json
Not sure when the command disappeared, but here it is
=> fix: re-add clear data script as npm command

server/services/phase.js
Realized while looking through prod data that participant statuses refer to a site's `siteId` rather than a site's `id`. You can see examples of this in the `employerSpecificJoin` and other such joins.
This should fix the phases request
=> fix: status sites relate to siteID not site.id

server/tests/phase.service.test.js
Just adding a test for get site phases, to ensure that participants hired within a certain phase is properly detected.
Do we need to add more cases? Does this make more sense in the e2e suite?
=> fix: add a test for getting all site phases

client/src/pages/private/SiteTableAllocation.js, server/services/employers.ts, server/services/phase.ts, server/utils.ts
- added formatter on the BE to remove timezone/formate date, (Open to suggestions for a better name)
- updated responses that were using similar logic for phase dates,
- the FE is now returned null/undefined vs Invalid Date. 
- Updated FE site table to check for phase start_date vs displaying string Invalid Date
vs.
=> Updated phase date response

server/services/employers.ts, server/tests/employer.site.e2e.test.js, server/tests/employer.site.test.js
- updated `getSiteByID` to include a query to get the current phase allocation record. (This should be the same allocation visible on the site view table)
=> HCAP-1428 - Allocation not showing up on site detail view

client/src/components/modal-forms/ReturnOfServiceForm.js, client/src/constants/validation/schema/schema-edit-ros-site.js, client/src/constants/validation/schema/schema-return-of-service.js, cypress/integration/returnOfService.spec.js, server/tests/return-of-service.e2e.test.js, server/validators/return-of-service.ts
- added yup validation to make Employment type required
- removed `(optional)` from form Label
- added server tests for failure 
- added cypress test to test for required fields on the form.
=> Feature - HCAP-1429 - Make ROS emoloyment type required

client/src/components/modal-forms/BulkAllocationForm.js, client/src/constants/validation/schema/schema-create-site.js, client/src/constants/validation/schema/schema-edit-site.js, client/src/constants/validation/schema/schema-employer-form.js, client/src/pages/private/SiteViewDetails.js, client/src/utils/gen-util.js, cypress/integration/siteViewDetails.spec.js, server/tests/employer.site.e2e.test.js, server/validators/employer.ts
- Added max 255 characters for siteName on all yup validations
- Added tests to check failure if siteName is too long.
- Used addEllipsisMask on the link and modal header for siteName if over 50 characters (For the link - the full site name is displayed directly under, for the modal header if the siteName was too long the modal wouldn't scroll thus preventing editing. The full name is still visible in the form)
- Deleted the `truncateString` function as a function already existed that did the same thing. `addEllipsisMask`
=> HCAP-1461 - Site name too long

client/src/pages/private/UserView.js, server/keycloak.ts
Sets the pending users to have a max like most other user requests. (Likely not a long term solution).
Sets brief representation as well, as it's not necessary to get more info than that
=> fix: increase pending users limit

client/src/components/modal-forms/ManageGraduationForm.js, client/src/constants/validation/schema/schema-participant-post-hire-status.js
- Since the graduation date was previously populated and disabled, there was no way for the user to clear the form before submitting. Added required to yup. 
- Updated logic surrounding `isGraduatingBeforeCohortEndDate`, this now disables the form before being submitted and prevents users from graduating a participant before the cohort has ended.
=> HCAP-1469 - fix validations on graduation date

client/src/pages/private/ParticipantTable.js, cypress/fixtures/participantTableTabs.json, cypress/integration/participantStatus.spec.js, server/routes/participant.ts, server/tests/employer-action.e2e.test.ts
Note - The FE isn't using the `employer-actions/bulk-engage` API, it is looping through participants and hitting `employer-actions`, so I did not make any changes to the permissions of that API as employers can still engage participants individually. (The FE is currently making 3 API calls per participant in the bulk engage list)
- removed employer permission from bulk-engage API (although it's deprecated/only being used by tests) 
- updated test suites to include failure if unauthenticated, 
- added check for HA on UI to see multi-select and bulk engage button
HA view:
Employer view:
=> HCAP-1449 - Remove ability for employer to bulk engage participants

client/src/constants/siteDetailsConstants.js, client/src/pages/private/SiteTable.js
- For the upcoming release, I wrapped the allocations column and positions overview in a feature flag as they were the only part of the allocation work not in a feature flag. 
Details page without Position Overview
Site table without allocation:
=> Feature Flagging

server/migrations/1661465391816_allocation_migration.js
Commenting out this line for now so we don't remove the current allocations of sites
This is strictly in case we need to rollback. I created https://eydscanada.atlassian.net/browse/HCAP-1477 for this.
=> fix: comment out site allocation removal

client/src/constants/siteDetailsConstants.js, server/services/employers.ts, server/tests/employer.site.test.ts
- Site detail page is now displaying the correct count for HCAP Hires and non-HCAP hires. (same logic used on the allocation table view)
If there is no allocation or current phase, count displays as 0
=> HCAP-1346 - HCAP and nonHCAP hire count bug fix

server/services/participant-details.ts
Viewing some participants was returning a 500 error due to some statuses having null data
=> fix: add optional for pstatus without site

cypress.json, cypress/integration/cohortView.spec.js, cypress/integration/participantStatus.spec.js, cypress/integration/participantTable.spec.js, cypress/integration/psiDetailView.spec.js, cypress/integration/setAllocation.spec.js, cypress/integration/userView.spec.js
- Possible fix to unreliable cypress tests. 
- Removed default timeout override
- Instead of using an arbitrary cy.wait, Updated the test to listen for the GET request to resolve before checking the DOM for an element.
=> Cypress updates to inconsistent tests

openshift/in-progres-stale-clean.cronjob.yml, openshift/open-expired-clean.cronjob.yml, server/package.json
This moves the logic to npm commands that the cron job can hit. This is due to the typescript change.
=> fix: cron job paths were no longer working

.docker/keycloak/realm-testing.json, .docker/keycloak/users.json, server/middleware/access-logger.ts, server/routes/participant-user.ts
- added user_id attributes to local keycloak users to prevent null userId's being returned
- ~~user id for bcsc login is now called `bcsc_guid`~~ **no longer needed**
- ~~added bcsc_guid attribute to test participant~~ **no longer needed**
- ~~added bcsc_guid client scope mapper for FE client so it is included in token~~ **no longer needed**
=> add option for bcsc id and add user_id attr to keycloak users

server/keycloak.ts
- add guard for scenarios where `email` is undefined
- prevent user migration from running if there is no `email`
- add `email` check in `migrateUser` function
=> fix: add email guard for user info middleware and email check for user migration

server/services/health-check.ts
The Keycloak team reached out and said we were making way more requests than necessary, and this is believed to be due to the liveness / readiness probes. We shouldn't need to check KC for our health check; if its down, we may not necessarily want the whole application to be down (which the liveness probe will do before this change).
=> fix: removing keycloak health check

client/src/constants/archiveParticipantsConstants.js
- Remove 'other' option
- Add options:
- No longer interested in a career in mental health and substance use sector
- No longer interested in MHASW / MHAW role
=> HCAP-1496 update participant withdrawal reasons

client/src/components/participant-form/sections/HCAPProgramSection.js
- add text to let participants know to apply twice if they are interested in both streams.
Text: Please Note: Please submit a separate application for each program if you are interested in both.
Under “HCAP Program” and above “1. * Which program are you applying for?”
[HCAP-1509](https://eydscanada.atlassian.net/jira/software/c/projects/HCAP/boards/206?selectedIssue=HCAP-1509)
=> add text explaining to participants to apply twice 

server/services/participants-helper/FieldsFilteredParticipantsFinder.ts, server/services/participants-helper/RegionsFilteredParticipantsFinder.ts
- update query to include indigenous field from PEOI question -> changed to an `or`
- update query for super users to prevent overwriting if `or` query exists from indigenous filter
=> HCAP-1507 - update indigenous only filter to include new question on PEOI

client/src/components/modal-forms/NewParticipantForm.js, client/src/constants/participantDetailsConstants.js, client/src/constants/validation/schema/schema-external-hired-participant.js, client/src/services/participant-details.js, server/routes/participant.ts, server/validators/external-participant.ts
- change preferred locations to single select
- change options to only include HA's from users roles
- update text for Lived/ Living Expense to `Lived/Living Experience with MHSU`
- add item for `How did they learn about HCAP?` in participant details
- [HCAP-1523](https://eydscanada.atlassian.net/jira/software/c/projects/HCAP/boards/206?selectedIssue=HCAP-1523)
- [HCAP-1521](https://eydscanada.atlassian.net/jira/software/c/projects/HCAP/boards/206?selectedIssue=HCAP-1521)
- [HCAP-1522](https://eydscanada.atlassian.net/jira/software/c/projects/HCAP/boards/206?selectedIssue=HCAP-1522)
=> HCAP - updates to non portal form

openshift/server.dc.yml, server/db/db.ts, server/routes/milestone-report.ts, server/services/reporting/participants-report.ts
Implemented Streaming in server/routes/milestone-report.ts (rewrote the generateHiredReport function to use a batched approach)
Fetches data in batches of 500 records
Processes each batch and writes it to the CSV stream immediately
Continues until no more records are found
Logs progress periodically and at completion
=> add pagination to hiring report and increased the timeout to 60s

server/services/reporting/milestones-report.ts
Modified the database query in server/services/reporting/milestones-report.ts to directly pass the array of participant IDs without using the $in operator syntax
=> fix the ROS report error

.github/workflows/format.yml, .github/workflows/promote-dev.yml, .github/workflows/promote-test.yml, .github/workflows/sonar.yml, .github/workflows/test.yml, Makefile, docs/deployment.md
Format Check:
1st check: Runs on PRs opened, synchronized, or reopened to ANY branch (Analyzes the current feature branch and does not compare against any branch)
Sonar Check:
1st check: Runs on PRs opened, synchronized, or reopened to ANY branch (Analyzes the current feature branch but compares against target branch (e.g. dev-env))
2nd check: Runs on direct pushes to master, dev-env, and test-env branches (Analyzes the target branch (e.g. dev-env))
Cypress/Jest Tests:
1st check: Runs when a tag named "cypress" is pushed (Analyzes the current feature branch)
OR
Runs on PRs opened, synchronized, or reopened to master, dev-env, and test-env branches only (Analyzes the current feature branch)
Dev Deployment:
Deployments to the development environment can be triggered by these 3 approaches: …
=> Add separate branches (dev-env and test-env) for the development and test environments.

.github/workflows/format.yml, .github/workflows/promote-dev.yml, .github/workflows/promote-test.yml, .github/workflows/sonar.yml, .github/workflows/test.yml, .gitignore, Makefile, client/src/utils/keycloak-util.js, docs/deployment.md, server/keycloak.ts, server/scripts/export-user-ha.ts, server/services/reporting/milestones-report.ts, server/services/reporting/ros-entries.ts
This PR includes the following updates:
1. New Branches Added:
dev-env and test-env branches have been introduced.
2. Updated GitHub Actions Behavior:
Format Check
Trigger: Runs on PRs that are opened, synchronized, or reopened to any branch.
Analysis: Evaluates the current feature branch without comparing against any other branch.
Sonar Check
PR Check: Runs on PRs opened, synchronized, or reopened to any branch. Compares the current feature branch against the target branch (e.g., dev-env).
Push Check: Runs on direct pushes to master, dev-env, and test-env branches. Analyzes the target branch directly.
Cypress/Jest Tests
Tag Trigger: Runs when a Git tag named cypress is pushed, analyzing the current feature branch.
PR Trigger: Also runs on PRs opened, synchronized, or reopened to master, …
=> Add dev-env&test-env branches; update ROS report query; add KeyCloak login option

.github/workflows/promote-dev.yml, .github/workflows/promote-prod.yml, .github/workflows/promote-test.yml, Makefile
Summary of Changes:
1. Fixed OpenShift CLI Installation on Test&Prod deployment workflow files to match the existing dev workflow pattern
2. Added Cronjob management to all deployment workflows (promote-dev.yml, promote-test.yml, promote-prod.yml), cronjobs now automatically update when openshift/** files change
=> Openshift CLI install method update and cronjob management

.github/workflows/promote-dev.yml, client/src/constants/routes.js, docs/deployment.md, load/employerStaticFiles.js, load/participantLogin.js, openshift/ches.prep.yml
Description of changes:
- updating Regex to support the following domains while not breaking current domains:
- https://dev.hcapparticipants.gov.bc.ca
- https://dev.hcapemployers.gov.bc.ca
- https://test.hcapparticipants.gov.bc.ca
- https://test.hcapemployers.gov.bc.ca
=> BCMOHAM-26040: Domain migration for DEV and TEST

server/server.ts
Fix SPA catch-all route for Express 5 / path-to-regexp v6
=> Fix SPA catch-all route for Express 5 / path-to-regexp v6

client/src/components/modal-forms/EditParticipantForm.js, client/src/constants/validation/schema/index.js, client/src/constants/validation/schema/schema-create-site.js, client/src/constants/validation/schema/schema-edit-participant-form.js, client/src/constants/validation/schema/schema-edit-site.js, client/src/constants/validation/schema/schema-edit-user-migration-user.js, client/src/constants/validation/schema/schema-employer-form.js, client/src/constants/validation/schema/schema-external-hired-participant.js
This PR fixes the email validation issue on the "Edit Participant" pop-up and "Add New Non-Portal Hire" pop-up, ensuring that inputs like "user@example" are correctly flagged as invalid
=> fix the email validation on participant info edit pop-up
